= 基本的な依存関係
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc-title: TUTORIAL - SIMPLE DEPENDENCY
:toclevels: 3
:native: Motoko
:lang: Rust
:platform: Internet Computer プラットフォーム
:LEE: ローカル Canister 実行環境
:IC: Internet Computer blockchain
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:cdk-short-name: DFINITY Rust CDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust

Dapp デザインのよくあるアプローチは、ある Canister スマートコントラクト（あるいは単に Canister と呼ぶ）でデータを計算または保存し、それを別の Canister で使用するというものです。
たとえ基盤となるスマートコントラクトが異なる言語で書かれていても、異なる Canister のスマートコントラクトで定義された関数を共有して使用できることは、{IC} で動作する Dapps を構築する際の重要な戦略となります。
このチュートリアルでは、ある言語（今回の例では {native}）で関数を書き、そのデータを別の言語（ここでは{lang}）で使用する方法を紹介します。

両方の Canister スマートコントラクトは同じプロジェクトに含まれています。

* {native} Canister は オペレーションの結果を保存するための `+cell+` 変数を持つ Actor を作成します。
* `+mul+` 関数は自然数を入力として受け取り、入力値を３倍にして、結果を `+cell+` 変数に格納します。
* {lang} Canister は `+cell+` 変数の現在の値を返す `+read+` 関数を持ちます。

== はじめる前に

プロジェクトをはじめる前に、以下を確認してください:

* インターネットに接続しており、ローカルの macOS または Linux コンピュータでターミナルにアクセスできること。

* link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust のインストール方法] にあるように、Rust プログラミング言語と Cargo が OS にダウンロードされ、インストールされていること。

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
Rust のバージョンは 1.46.0 より新しい必要があります。

* link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[ダウンロードとインストール]の説明に従って、{sdk-long-name} パッケージのダウンロードとインストールが済んでいること。

* `+cmake+` のインストールが済んでいること。例えば、macOS では Homebrew を使って以下のコマンドを実行します:
+
[source,bash]
----
brew install cmake
----
Homebrew をインストールする方法については、link:https://docs.brew.sh/Installation[Homebrew のドキュメント]を参照してください。

* コンピュータ上の {LEE} プロセスが停止していること。

ローカルコンピュータ上で新たなターミナルを開く方法や、ターミナルでコマンドを実行する方法や、インストールパッケージを確認する方法がわからない場合には、link:../quickstart/newcomers{outfilesuffix}[初めての人のための準備]を参照してください。
既に必要な前提条件を満たしている場合には、<<create-a-new-project,新しいプロジェクトの作成>> へと進んでください。

このチュートリアルは、完走に約 20 分かかります。

[[create-a-new-project]]
== 新しいプロジェクトの作成

新しいプロジェクトを作る手順は以下になります:

[arabic]
. ローカル PC でターミナルを開きます。
. 以下のコマンドを実行し、`+multiply_deps+` という名前の新しいプロジェクトを作成します。
+
[source,bash]
----
dfx new multiply_deps
----
. 以下のコマンドで、プロジェクトディレクトリに移動します。
+
[source,bash]
----
cd multiply_deps
----

== デフォルト設定の変更

新しいプロジェクトを作成すると、`+cargo new+` コマンドを使ったときと同じように、いくつかのテンプレートファイルがプロジェクトディレクトリに追加されます。
{IC} 上で動作する Canister スマートコントラクトを構築する前に、いくつか Rust 固有のファイルをプロジェクトに追加する必要があります。

{proglang} プロジェクトのデフォルト設定を変更するには、以下の手順を踏みます。

* <<edit-the-default-canister-settings, Canister の初期設定の変更>>
* <<add-a-cargotoml-file-to-the-project, Cargo.toml ファイルの追加>>
* <<add-Rust-files-to-the-source-directory, src ディレクトリへの Rust ファイルの追加>>
* <<replace-the-default-motoko-canister, デフォルトの {native} Canister の置き換え>>
* <<replace-the-default-rust-canister, デフォルトの {lang} Canister の置き換え>>

[[edit-the-default-canister-settings]]
=== Canister の初期設定の変更

このサンプルプロジェクトは、{native} Canister と {lang} Canister の２つの Canister で構成されているため、デフォルトの `+dfx.json+` 設定ファイルを変更し、{native} Canister と {lang} Canister の両方をビルドするための情報を含める必要があります。

`+dfx.json+` を変更するには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. テキストエディタで `+dfx.json+` を開きます。
. `+canisters.multiply_deps+` セクションの下に、 `+cargo build+` コマンドを使って {lang} プログラムをビルドするための設定を挿入します。
+
例えば、`+canisters+` セクションの中で、新しい `+rust_deps+` キーを以下のように追加します：
+
[source,json]
----
"rust_deps": {
  "build": "cargo build --target wasm32-unknown-unknown --package  rust_deps --release",
  "candid": "src/rust_deps/src/deps.did",
  "wasm": "target/wasm32-unknown-unknown/release/rust_deps.wasm",
  "type": "custom"
  }
----
. `+multiply_deps_assets+` のセクションから `+dependencies+` の設定をコピーし、{lang} Canister の設定に追加します。
`+dependencies+` の設定では、ある Canister から関数をインポートし、別の Canister で使用することができます。
このチュートリアルでは、{native} で書かれた `+multiply_deps+` Canister から関数をインポートし、Rust で書かれた `+rust_deps+` Canister から使用することを考えます。
. ファイルから `+multiply_deps_assets+` の設定をすべて削除します。
+
このチュートリアルの Dapp では、フロントエンドの `asset` を使用していないので、設定ファイルからこれらの設定を削除することができます。
+
また、このチュートリアルでは `+defaults+` と `+dfx+` のキーも削除することができます。
+
これらの不要な設定を削除した後の設定ファイルは次のようになります:
+
....
include::example$mul-deps/mul-deps-dfx.json[]
....
. 変更内容を保存し、`+dfx.json+` ファイルを閉じて次に進みます。

[[add-a-cargotoml-file-to-the-project]]
=== Cargo.toml ファイルの追加

`+cargo build+` コマンドを使って {lang} Canister をビルドするために、プロジェクトディレクトリに `+Cargo.toml+` ファイルを追加する必要があります。

プロジェクトに `+Cargo.toml+` ファイルを追加するには、以下のようにします：

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. カレントディレクトリに `+Cargo.toml+` という名前のファイルを作成します.
. テキストエディタで `+Cargo.toml+` を開きます。
. `+[workspace]+` キーを使って Dapp のソースファイルのディレクトリを指定します:
+
[source,toml]
----
[workspace]
members = [
    "src/rust_deps",
]
----
. 変更内容を保存し、`+Cargo.toml+` ファイルを閉じて次に進みます。

[[add-Rust-files-to-the-source-directory]]
=== src ディレクトリへの Rust ファイルの追加

新しいプロジェクトを作成すると、`+src/multiply_deps+` ディレクトリが作成され、テンプレートとして `+main.mo+` が {native} Canister のために作成されます。

ここでは、{lang} Canister をビルドするためのファイルを追加していきます。

`src` ディレクトリに Rust ファイルを用意するのは、以下の手順となります:

. 自分がルートディレクトリにいることを確認します。
. 以下のコマンドを実行して、ライブラリテンプレートを使用した新しい Cargo パッケージを作成します:
+
[source, bash]
----
cargo init --lib src/rust_deps
----
+
このコマンドは `+src/rust_deps/src+` ディレクトリに、ライブラリ(`+lib.rs+`)パッケージと、`+Cargo.toml+` ファイルを作成します。
. `+src/rust_deps/Cargo.toml+` ファイルをテキストエディタで開きます。
+
このファイルを使って、Rustパッケージのビルドに関する詳細を設定します。
+
最小限の構成として、パッケージ名・クレートタイプ・使用する {cdk-short-name} ライブラリのバージョンなどの基本情報を以下のように設定する必要があります:
+
--
* `+[package]+`
* `+[lib]+`
* `+[dependencies]+`
--
. 既存の `+[dependencies]+` セクションを削除して、以下のように置き換えます:
+
[source,toml]
----
[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
----
+
NOTE: このあとのチュートリアルでアプリを実際にデプロイする際に、パッケージの依存関係が間違っているというエラーメッセージが表示されることがあります。もし新しいバージョンの {cdk-short-name} がある場合は、`+src/rust_deps/Cargo.toml+` ファイルの依存関係を最新バージョンに合わせて更新してください。
. 変更を保存してファイルを閉じ、次に進みます。

[[replace-the-default-motoko-canister]]
=== デフォルトの {native} Canister の置き換え

次のステップは、`+src/multiply_deps/main.mo+` ファイル内のソースコードを、`+mul+` と `+read+` の関数を実装したコードに置き換えることです。

デフォルトの {native} ソースコードを修正するには以下のようにします：

. 自分がルートディレクトリにいることを確認します。
. `+src/multiply_deps/main.mo+` ファイルをテキストエディタで開き、既存のコードを削除します。

. 以下のサンプルコードを `+main.mo+` ファイル内にコピー＆ペーストします：
+
[source,motoko]
----
include::example$mul-deps/mul-deps.mo[]
----
. 変更を保存してファイルを閉じ、次に進みます。

[[replace-the-default-rust-canister]]
=== デフォルトの {lang} Canister の置き換え

これで {lang} Canister が依存する {native} Canister ができたので、{lang} Canister をプロジェクトに追加してみましょう。

デフォルトの {lang} Canister を置き換えるには以下のようにします：

. 自分がルートディレクトリにいることを確認します。
. `+src/rust_deps/src/lib.rs+` ファイルをテキストエディタで開き、内容を削除します。
+
次のステップは、{native} Canister をインポートし、`+read+` 関数を実装した Rust プログラムを書くことです。
. `+lib.rs+` ファイルに以下のコードをコピー＆ペーストします：
+
[source,bash]
----
include::example$mul-deps/deps-main.rs[]
----
. `+src/rust_deps/src/lib.rs+` を保存して閉じ、先に進みます。

== インターフェイス記述ファイルの追加

Candid は、{IC} で動作する Canister と対話するためのインターフェース記述言語（IDL）です。
Candid ファイルは、Canister が定義する各関数の名前・引数・返し値のフォーマットやデータ型など、Canister のインターフェースを言語に依存しないように記述したものです。

Candid ファイルをプロジェクトに追加することで、Rust で定義されたデータが {IC} 上で安全に実行されるために適切に変換されることを保証します。

Candid インターフェース記述言語の構文の詳細は link:../candid-guide/candid-intro{outfilesuffix}[_Candid ガイド_]か https://docs.rs/candid/[Candid クレートのドキュメント]をご覧ください。

Candid ファイルを追加するには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. `+src/rust_deps/src+`　ディレクトリに、`+deps.did+` という名前のファイルを作成します。
. `+src/rust_deps/src/deps.did+` ファイルをテキストエディタで開きます。
. `+read+` 関数のために、以下のように `+service+` を定義します:
+
[source,did]
----
service : {
  "read": () -> (nat) query;
}
----
. 変更を保存して `+deps.did+` ファイルを閉じ、次に進んでください。

== {LEE} を立ち上げる

プロジェクトをビルドする前に、{LEE} か、{IC} メインネットに接続する必要があります。

{LEE} を立ち上げるには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. {LEE} をバックグラウンドで立ち上げるために、以下のコマンドを実行します:
+
[source,bash]
----
dfx start --clean --background
----
+
プラットフォームやローカルのセキュリティ設定によっては、警告が表示される場合があります。
ネットワーク接続を許可するかどうかの確認画面が表示された場合は、*Allow* をクリックします。

== プロジェクトの登録・ビルド・デプロイ

開発環境で立ち上がっている {LEE} に接続した後に、プロジェクトの登録・ビルド・デプロイをローカル環境で行うことができます。
登録・ビルド・デプロイを行うためには、以下のようにします:

. プロジェクトのルートディレクトリにいることを確認します。
. `+dfx.json+` に指定されている Canister を以下のコマンドで、登録・ビルド・デプロイします:
+
[source,bash]
----
dfx deploy
----
+
`+dfx deploy+` コマンドを実行すると、以下のような実行結果に関しての情報が表示されます。
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "pubs_user_id" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "multiply_deps"...
"multiply_deps" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "rust_deps"...
"rust_deps" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Executing 'cargo build --target wasm32-unknown-unknown --package  rust_deps --release'
   Compiling ic-cdk v0.3
   Compiling ic-cdk-macros v0.3
   Compiling rust_deps v0.1.0 (/Users/pubs/multiply_deps/src/rust_deps)
    Finished release [optimized] target(s) in 2m 09s
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "r7inp-6aaaa-aaaaa-aaabq-cai"
Installing code for canister multiply_deps, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
Installing code for canister rust_deps, with canister_id ryjl3-tyaaa-aaaaa-aaaba-cai
Deployed canisters.
....

== デプロイした Canister の関数を呼ぶ

Canister のデプロイが成功すると、Canister の関数を呼ぶことでテストできるようになります。

このチュートリアルでは、以下のようにします：

* `+mul+` 関数を呼ぶたびに、`+cell+` 変数の値を 3 倍にします。
* `+read+` 関数を呼び出し、`+cell+` 変数の現在の値を返します。

デプロイした Canister をテストするために：

. デプロイした Canister 上の `+cell+` 変数の値を読み取るために {native} Canister から `+read+` 関数を呼び出します。
+
[source,bash]
----
dfx canister call multiply_deps read
----
+
このコマンドは、変数 `+cell+` の現在の値である１を返します。
+
....
(1)
....
. 次のコマンドを実行して、入力された引数を３倍する `+mul+` 関数を呼び出します。
+
[source,bash]
----
dfx canister call multiply_deps mul '(3)'
----
+
このコマンドは、変数 `+cell+` の新しい値を返します。
+
....
(9)
....
. `+multiply_deps+` Canister から関数をインポートしている `+rust_deps+` Canister の `+read+` 関数を呼び出します。
+
[source,bash]
----
dfx canister call rust_deps read
----
+
このコマンドは、変数 `+cell+` の現在の値を返します。
+
....
(9)
....

== {LEE} を止める

アプリケーションのテストをした後は、{LEE} がバックグラウンドで稼働し続けないように、以下の手順で停止します：

. ネットワークの稼働状況が表示されている端末で、Control-C を押して {LEE} のプロセスを止めてください。

. 以下のコマンドを用いて {LEE} を停止してください：
+
[source,bash]
----
dfx stop
----

////
= Basic dependency
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc-title: TUTORIAL - SIMPLE DEPENDENCY
:toclevels: 3
:native: Motoko
:lang: Rust
:platform: Internet Computer platform
:LEE: local canister execution environment
:IC: Internet Computer blockchain
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:cdk-short-name: DFINITY Rust CDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust

One common approach to dapp design is to calculate or store data in one canister smart contract – or canister for short – that you can then use in another canister.
This ability to share and use functions defined in different canister smart contracts, even if the underlying smart contracts are written in different languages, is an important strategy for building dapps to run the {IC}.
This tutorial provides a basic introduction to how you can write functions in one language—in the example, {native}—then use the data in another—in this case, {lang}.

For this tutorial, both canister smart contracts are in the same project.

* The {native} canister creates an actor with a `+cell+` variable to contain the current value that results from an operation.
* The `+mul+` function takes a natural number as input, multiplies the input value by three and stores the result in the `+cell+` variable.
* The {lang} canister provides a `+read+` function that is a simple query that returns the current value of the `+cell+` variable.

== Before you begin

Before you start your project, verify the following:

* You have an internet connection and access to a shell terminal on your local macOS or Linux computer.

* You have downloaded and installed the Rust programming language and Cargo as described in the link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust installation instructions] for your operating system.

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
The Rust tool chain must be at version 1.46.0, or later.

* You have downloaded and installed the {sdk-long-name} package as described in link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].

* You have `+cmake+` installed. For example, use Homebrew with the following command:
+
[source,bash]
----
brew install cmake
----
For instructions on how to install Homebrew, see the link:https://docs.brew.sh/Installation[Homebrew Documentation].

* You have stopped any {LEE} processes running on your computer.

If you aren’t sure how to open a new terminal shell on your local computer, run commands in a terminal, or how to check for and install packages, see link:../quickstart/newcomers{outfilesuffix}[Preliminary steps for newcomers].
If you are comfortable meeting the prerequisites without instructions, continue to <<Create a new project,Create a new project>>.

This tutorial takes approximately 20 minutes to complete.

== Create a new project

To create a new project directory for this tutorial:

[arabic]
. Open a terminal shell on your local computer, if you don’t already have one open.
. Create a new project by running the following command:
+
[source,bash]
----
dfx new multiply_deps
----
. Change to your project directory by running the following command:
+
[source,bash]
----
cd multiply_deps
----

== Modify the default configuration

creating a new project adds several template files to your project directory much like when you create a new Rust package using the `+cargo new+` command.
You need to modify these default files and add some Rust-specific files to your project before you can build canisters that run on the {IC}.

To modify the default configuration for a {proglang} project, you'll need to complete the following steps:

* <<Edit the default canister settings>>
* <<Add a Cargo.toml file to the project>>
* <<Add Rust files to the source directory>>
* <<Replace the default {native} canister>>
* <<Replace the default {lang} canister>>

=== Edit the default canister settings

Because this sample project is going to consist of two canisters-the {native} canister and the {lang} canister—you need to modify the default `+dfx.json+` configuration file to include information for building both the {native} canister and a {lang} canister.

To modify the `+dfx.json+` configuration file:

. Check that you are still in the root directory for your project, if needed.
. Open the `+dfx.json+` configuration file in a text editor.
. Insert a new section after the `+canisters.multiply_deps+` settings with settings for building a {lang} program using the `+cargo build+` command.
+
For example, in the `+canisters+` section, add a new `+rust_deps+` key with settings like these:
+
[source,json]
----
"rust_deps": {
  "build": "cargo build --target wasm32-unknown-unknown --package  rust_deps --release",
  "candid": "src/rust_deps/src/deps.did",
  "wasm": "target/wasm32-unknown-unknown/release/rust_deps.wasm",
  "type": "custom"
  }
----
. Copy the `+dependencies+` setting from the `+multiply_deps_assets+` section and add it to the settings for the {lang} canister.
+
The `+dependencies+` setting enables you to import functions from one canisters for use in another canister. For this tutorial, we want to import a function from the `+multiply_deps+` canister—written in {native}—and use it from the `+rust_deps+` canister written in Rust.
. Remove all of the `+multiply_deps_assets+` configuration settings from the file.
+
The sample dapp for this tutorial doesn't use any front-end assets, so you can remove those settings from the configuration file.
+
You can also remove the `+defaults+` and `+dfx+` version settings.
+
For example, your configuration file might look like this after you modify the settings:
+
....
include::example$mul-deps/mul-deps-dfx.json[]
....
. Save your change and close the `+dfx.json+` file to continue.

=== Add a Cargo.toml file to the project

To build the {lang} canister using the `+cargo build+` command we added to the `+dfx.json+` configuration file, we also need to add a `+Cargo.toml+` file to the project directory.

To add `+Cargo.toml+` settings for the project:

. Check that you are still in the root directory for your project, if needed.
. Create a new file in the current directory named `+Cargo.toml+`.
. Open the `+Cargo.toml+` in a text editor.
. Use the `+[workspace]+` key to specify the source file directory for your canister.
+
For example:
+
[source,toml]
----
[workspace]
members = [
    "src/rust_deps",
]
----
. Save your changes and close the `+Cargo.toml+` file to continue.

=== Add Rust files to the source directory

Creating a new project creates a default `+src/multiply_deps+` directory with a template `+main.mo+` for our {native} canister.
For this tutorial, we want to add the files for building a {lang} canister.

To prepare the source directory with Rust files:

. Check that you are in the root directory for your project, if needed.
. Create a new cargo package using a library template by running the following command:
+
[source, bash]
----
cargo init --lib src/rust_deps
----
+
This command creates a `+src/rust_deps/src+` directory with a library (`+lib.rs+`) package and a `+Cargo.toml+` file in the `+src/rust_deps+` directory.
. Open the `+src/rust_deps/Cargo.toml+` file in a text editor.
+
You use this file to configure the details used to build the Rust package.
+
At a minimum, you need to configure the following sections with basic information about the package name, the crate type, and the version of the {cdk-short-name} libraries to use.
+
--
* `+[package]+`
* `+[lib]+`
* `+[dependencies]+`
--
. Delete the existing `+[dependencies]+` section and replace it with the following:
+
[source,toml]
----
[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
----
+
NOTE: When you deploy the dapp later in the tutorial, you might get an error message that the dependency version is wrong. If there is a newer version of the {cdk-short-name}, update the dependencies in the `+src/rust_deps/Cargo.toml+` file to match the latest version.
. Save your changes and close the file to continue.

=== Replace the default {native} canister smart contract

The next step is to replace the default source code in the `+src/multiply_deps/main.mo+` file with code that implements the `+mul+` and `+read+` functions.

To modify the default {native} source code:

. Check that you are still in the root directory for your project, if needed.
. Open the `+src/multiply_deps/main.mo+` file in a text editor and delete the existing content.
. Copy and paste the following sample code into the `+main.mo+` file:
+
[source,motoko]
----
include::example$mul-deps/mul-deps.mo[]
----
. Save your changes and close the file to continue.

== Replace the default {lang} canister smart contract

Now that we have the {native} canister that the {lang} canister depends upon, let's add the {lang} canister to the project.

To replace the default {lang} canister:

. Check that you are still in the root directory for your project, if needed.
. Open the template `+src/rust_deps/src/lib.rs+` file in a text editor and delete the existing content.
+
The next step is to write a Rust program that imports the {native} canister and implements the `+read+` function.
. Copy and paste the following sample code into the `+lib.rs+` file:
+
[source,bash]
----
include::example$mul-deps/deps-main.rs[]
----
. Save your changes and close the `+src/rust_deps/src/lib.rs+` file to continue.

== Add an interface description file

Candid is an interface description language (IDL) for interacting with canisters running on the {IC}.
Candid files provide a language-independent description of a canister's interfaces including the names, parameters, and result formats and data types for each function a canister defines.

By adding Candid files to your project, you can ensure that data is properly converted from its definition in Rust to run safely on the {IC}.

To see details about the Candid interface description language syntax, see the link:../candid-guide/candid-intro{outfilesuffix}[_Candid Guide_] or the https://docs.rs/candid/[Candid crate documentation].

To add a Candid file for this tutorial:

. Check that you are still in the root directory for your project, if needed.
. Create a new file named `+deps.did+` in the `+src/rust_deps/src+` directory.
. Open the `+src/rust_deps/src/deps.did+` file in a text editor.
. Copy and paste the following `+service+` definition for the `+read+` function:
+
[source,did]
----
service : {
  "read": () -> (nat) query;
}
----
. Save your changes and close the `+deps.did+` file to continue.

== Start the {LEE}

Before you can build the project, you need to connect to the {LEE} in your development environment or the {IC} mainnet.

To start the network locally:

. Check that you are still in the root directory for your project, if needed.
. Start the {LEE} on your computer in the background by running the following command:
+
[source,bash]
----
dfx start --clean --background
----
+
Depending on your platform and local security settings, you might see a warning displayed.
If you are prompted to allow or deny incoming network connections, click *Allow*.

== Register, build, and deploy your project

After you connect to the {LEE} running in your development environment, you can register, build, and deploy your project locally.

To register, build, and deploy:

. Check that you are still in root directory for your project directory, if needed.
. Register, build, and deploy the canisters specified in the `+dfx.json+` file by running the following command:
+
[source,bash]
----
dfx deploy
----
+
The `+dfx deploy+` command output displays information about each of the operations it performs similar to the following excerpt:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "pubs_user_id" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "multiply_deps"...
"multiply_deps" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "rust_deps"...
"rust_deps" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Executing 'cargo build --target wasm32-unknown-unknown --package  rust_deps --release'
   Compiling ic-cdk v0.3
   Compiling ic-cdk-macros v0.3
   Compiling rust_deps v0.1.0 (/Users/pubs/multiply_deps/src/rust_deps)
    Finished release [optimized] target(s) in 2m 09s
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "r7inp-6aaaa-aaaaa-aaabq-cai"
Installing code for canister multiply_deps, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
Installing code for canister rust_deps, with canister_id ryjl3-tyaaa-aaaaa-aaaba-cai
Deployed canisters.
....

== Call functions on the deployed canister

After successfully deploying the canister, you can test the canister by invoking the functions it provides.

For this tutorial:

* Call the `+mul+` function to multiply the value of the `+cell+` variable by three each time it is called.
* Call the `+read+` function to return the current value of the `+cell+` variable.

To test the deployed canister:

. Call the `+read+` function from the {native} canister, which reads the current value of the `+cell+` variable on the deployed canister:
+
[source,bash]
----
dfx canister call multiply_deps read
----
+
The command returns the current value of the `+cell+` variable as one:
+
....
(1)
....
. Call the `+mul+` function to multiply the input argument by three by running the following command:
+
[source,bash]
----
dfx canister call multiply_deps mul '(3)'
----
+
The command returns the new value of the `+cell+` variable:
+
....
(9)
....
. Call the `+read+` function using the `+rust_deps+` canister that imports functions from the `+multiply_deps+` canister:
+
[source,bash]
----
dfx canister call rust_deps read
----
+
The command returns the current value of the `+cell+` variable:
+
....
(9)
....

== Stop the {LEE}

After you finish experimenting with your dapp, you can stop the {LEE} so that it doesn’t continue running in the background.

To stop the {LEE}:

. In the terminal that displays network operations, press Control-C to interrupt the {LEE} process.

. Stop the {LEE} by running the following command:
+
[source,bash]
----
dfx stop
----

////