= カウンターのインクリメント
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:LEE: ローカル Canister 実行環境
:sdk-short-name: DFINITY Canister SDK
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust
:company-id: DFINITY
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:cdk-short-name: DFINITY Rust CDK
:proglang: Rust
:platform: Internet Computer platform
:IC: Internet Computer blockchain
:toc-title: TUTORIAL - SIMPLE PERSISTENCE
:toclevels: 3

このチュートリアルでは、いくつかの簡単な関数によってカウンターの値をインクリメントする Dapp を作り、値の永続性について説明します。

この Dapp は、カウンターの値（自然数）を格納する可変型変数として、 `+COUNTER+` を宣言しています。
ここで以下の関数を考えます：

* `+increment+` : 現在の値を更新する関数です。値を１ずつ増加させ、戻り値はありません。
* `+get+` : カウンターの現在の値を返すシンプルなクエリ関数です。
* `+set+` : 引数で指定した数値にカウンターの値を更新する関数です。

このチュートリアルでは、Canister スマートコントラクトにデプロイされた Canister の関数を呼び出して、カウンターの値をインクリメントする簡単な例を示します。
値を増加させる関数を複数回呼び出すことで、呼び出しの間に変数の値が変わらないこと（値の永続性）を確認できます。

他のサンプル Dapps と同じように、このチュートリアルはシンプルでありながら現実的なワークフローのデモンストレーションとなっています:

* 新しいプロジェクトを作成します。
* WebAssembly モジュールにコンパイルされる Dapp を書きます。
* {LEE} に Canister をデプロイします。
* Canister スマートコントラクトのメソッドを呼び出して、カウンターの値をインクリメントしたり読んだりします。

[[before-you-begin]]
== はじめる前に

プロジェクトをはじめる前に、以下を確認します:

* インターネットに接続しており、ローカルの macOS または Linux コンピュータでターミナルにアクセスできること。

* link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust のインストール方法] にあるように、Rust プログラミング言語と Cargo が OS にダウンロードされ、インストールされていること。

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
Rust のバージョンは 1.46.0 より新しい必要があります。

* link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[ダウンロードとインストール]の説明に従って、{sdk-long-name} パッケージのダウンロードとインストールが済んでいること。

* `+cmake+` のインストールが済んでいること。例えば、macOS では Homebrew を使って以下のコマンドを実行します:
+
[source,bash]
----
brew install cmake
----
Homebrew をインストールする方法については、link:https://docs.brew.sh/Installation[Homebrew のドキュメント]を参照してください。

* コンピュータ上の {LEE} プロセスが停止していること。

ローカルコンピュータ上で新たなターミナルを開く方法や、ターミナルでコマンドを実行する方法や、インストールパッケージを確認する方法がわからない場合には、link:../quickstart/newcomers{outfilesuffix}[初めての人のための準備]を参照してください。
既に必要な前提条件を満たしている場合には、<<create-a-new-project,新しいプロジェクトの作成>> へと進んでください。

このチュートリアルは、完走に約 20 分かかります。

[[create-a-new-project]]
== 新しいプロジェクトの作成

新しいプロジェクトを作る手順は以下になります:

[arabic]
. ローカル PC でターミナルを開きます。
. 以下のコマンドを実行し、`+rust_counter+` という名前の新しいプロジェクトを作成します。
+
[source,bash]
----
dfx new rust_counter
----
+
. 以下のコマンドで、プロジェクトディレクトリに移動します。
+
[source,bash]
----
cd rust_counter
----

== デフォルト設定の変更

link:rust-quickstart{outfilesuffix}[Hello World! Rust CDK クイックスタート]では、（ちょうど `+cargo new+` で Rust の新しいパッケージを作るのと同じように）`+dfx new+` コマンドで新しいプロジェクトを作るとプロジェクトディレクトリにいくつかのテンプレートファイルが生成されることを学びました。
{IC} 上で動作する Canister スマートコントラクトを構築する前に、いくつか Rust 固有のファイルをプロジェクトに追加する必要があります。

{proglang} プロジェクトのデフォルト設定を変更するには、以下の手順を踏みます。

* <<edit-the-default-canister-settings, Canister の初期設定の変更>>
* <<add-a-cargotoml-file-to-the-project, Cargo.toml ファイルの追加>>
* <<add-Rust-files-to-the-source-directory, src ディレクトリへの Rust ファイルの追加>>
* <<replace-the-default-dapp, デフォルト Dapp の置き換え>>

[[edit-the-default-canister-settings]]
=== Canister の初期設定の変更

プロジェクトディレクトリに含まれるテンプレートファイルの一つに、`+dfx.json+` 設定ファイルがあります。
このファイルには {IC} で動かすプロジェクトをビルドするために必要な設定が含まれています。
これは `+Cargo.toml+` ファイルが Rust プログラムのビルドやパッケージ管理の設定を含んでいるのと同じです。
Canister スマートコントラクトとして Rust の Dapps をビルドするには、`+dfx.json+` のデフォルト設定を変更する必要があります。

`+dfx.json+` を変更するには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. テキストエディタで `+dfx.json+` を開きます。
. `+canisters.rust_counter+` の設定を、`+cargo build+` コマンドを使って Canister をビルドする設定に置き換えます。
+
例えば、`+rust_counter+` キーの下で、`+main+` と `+type+` を以下のように設定します:
+
[source,json]
----
  "rust_counter": {
    "build": "cargo build --target wasm32-unknown-unknown --package  rust_counter --release",
    "candid": "src/rust_counter/counter.did",
    "wasm": "target/wasm32-unknown-unknown/release/rust_counter.wasm",
    "type": "custom"
    }
----
. `+rust_counter_assets+` の設定をすべて削除します。
+
このチュートリアルの Dapp では、フロントエンドの `asset` を使用していないので、設定ファイルからこれらの設定を削除することができます。
また、このチュートリアルでは `+defaults+` と `+dfx+` のキーも削除することができます。
+
これらの不要な設定を削除した後の設定ファイルは次のようになります:
+
....
include::example$counter-tutorial/rust_counter_dfx.json[]
....
. 変更内容を保存し、ファイルを閉じて次に進みます。

[[add-a-cargotoml-file-to-the-project]]
=== Cargo.toml ファイルの追加

{IC} で動かすために {sdk-short-name} を使って新しい Rust プロジェクトを作っているので、プロジェクトディレクトリ内の特定の場所に Rust 固有のファイルを手動で作成する必要があります。
まず、プロジェクトのパッケージ情報を書くための `+Cargo.toml+` ファイルを作成しましょう。

プロジェクトに `+Cargo.toml+` ファイルを追加するには、以下のようにします：

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. カレントディレクトリに `+Cargo.toml+` という名前のファイルを作成します。
. テキストエディタで `+Cargo.toml+` を開きます。
. `+[workspace]+` キーを使って Dapp のソースファイルのディレクトリを指定します:
+
[source,toml]
----
[workspace]
members = [
    "src/rust_counter",
]
----
. 変更内容を保存し、ファイルを閉じて次に進みます。

[[add-Rust-files-to-the-source-directory]]
=== src ディレクトリへの Rust ファイルの追加

新しいプロジェクトを作成すると、`+src/rust_counter+` ディレクトリが作成され、テンプレートとして `+main.mo+` が作成されます。
このデフォルトの Dapp を、Rust の `+lib.rs+` パッケージと `+Cargo.toml+` ファイルで置き換えていきます。

`src` ディレクトリに Rust ファイルを用意するのは、以下の手順となります:

. 自分がルートディレクトリにいることを確認します。
. 以下のコマンドを実行して、ライブラリテンプレートを使用した新しい Cargo パッケージを作成します:
+
[source, bash]
----
cargo init --lib src/rust_counter
----
+
このコマンドは `+src/rust_counter/src+` ディレクトリに、ライブラリ(`+lib.rs+`)パッケージと、`+Cargo.toml+` ファイルを作成します。
. `+src/rust_counter/Cargo.toml+` ファイルをテキストエディタで開きます。
+
このファイルを使って、Rust パッケージのビルドに関する詳細を設定します。
+
最小限の構成として、パッケージ名・クレートタイプ・使用する {cdk-short-name} ライブラリのバージョンなどの基本情報を設定する必要があります:
+
--
* `+[package]+`
* `+[lib]+`
* `+[dependencies]+`
--
. 既存の `+[dependencies]+` セクションを削除して、以下のように置き換えます:
+
[source,toml]
----
[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
----
+
NOTE: このあとのチュートリアルでアプリを実際にデプロイする際に、パッケージの依存関係が間違っているというエラーメッセージが表示されることがあります。もし新しいバージョンの {cdk-short-name} がある場合は、`+src/rust_counter/Cargo.toml+` ファイルの依存関係を最新バージョンに合わせて更新してください。
. 変更を保存してファイルを閉じ、次に進みます。

[[replace-the-default-dapp]]
=== デフォルトの Dapp を置き換え

これで Rust Dapp 用のファイルが揃ったので、`+main.mo+` Dapp を Rust Dapp に置き換えていきます。

既存の Dapp を置き換えるには以下のようにします：

. 自分がルートディレクトリにいることを確認します。
. `+src/rust_hello/main.mo+` ファイルを以下のコマンドによって削除します:
+
[source,bash]
----
rm src/rust_counter/main.mo
----
. `+src/rust_hello/src/lib.rs+` ファイルをテキストエディタで開き、既存の内容を削除します。
+
次に、`+COUNTER+` 変数の定義と `+increment+` ・ `+get+` ・ `+set+` の３つの関数の実装を行っていきます。
. 下のサンプルコードを `+lib.rs+` にコピー＆ペーストしてください。
+
[source,motoko]
----
include::example$counter-tutorial/counter.rs[]
----
. 変更を保存してファイルを閉じ、次に進みます。

== インターフェイス記述ファイルの追加

Candid は、{IC} で動作する Canister と対話するためのインターフェース記述言語（IDL）です。
Candid ファイルは、Canister が定義する各関数の名前・引数・返し値のフォーマットやデータ型など、Canister のインターフェースを言語に依存しないように記述したものです。

Candid ファイルをプロジェクトに追加することで、Rust で定義されたデータが {IC} 上で安全に実行されるために適切に変換されることを保証します。

Candid インターフェース記述言語の構文の詳細は link:../candid-guide/candid-intro{outfilesuffix}[_Candid ガイド_]か https://docs.rs/candid/[Candid クレートのドキュメント]をご覧ください。

Candid ファイルを追加するには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. `+src/rust_counter/src/+` ディレクトリに、`+counter.did+` という名前でファイルを作成します。
. `+src/rust_counter/src/counter.did+` ファイルをテキストエディタで開き、 `+increment+` ・ `+get+` ・ `+set+` 関数のために以下の `+service+` の定義をコピー＆ペーストして書き込んでください。
+
[source,did]
----
service : {
  "increment": () -> ();
  "get": () -> (nat) query;
  "set": (nat) -> ();
}
----
. 変更を保存して `+counter.did+` ファイルを閉じ、次に進んでください。

[[start-the-local-network]]
== {LEE} を立ち上げる

`+rust_counter+` プロジェクトをビルドする前に、{LEE} か、{IC} メインネットに接続する必要があります。

{LEE} を立ち上げるには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. {LEE} をバックグラウンドで立ち上げるために、以下のコマンドを実行します:
+
[source,bash]
----
dfx start --background
----
+
プラットフォームやローカルのセキュリティ設定によっては、警告が表示される場合があります。
ネットワーク接続を許可するかどうかの確認画面が表示された場合は、*Allow* をクリックします。

[[register-ids]]
== プロジェクトの登録・ビルド・デプロイ

開発環境で立ち上がっている {LEE} に接続した後に、プロジェクトの登録・ビルド・デプロイをローカル環境で行うことができます。

登録・ビルド・デプロイを行うためには、以下のようにします:

. プロジェクトのルートディレクトリにいることを確認します。
. `+dfx.json+` に指定されている Canister を以下のコマンドで、登録・ビルド・デプロイします:
+
[source,bash]
----
dfx deploy
----
+
`+dfx deploy+` コマンドを実行すると、以下のような実行結果に関しての情報が表示されます。
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "pubs_user_id" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_counter"...
"rust_counter" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Building canisters...
Executing 'cargo build --target wasm32-unknown-unknown --package  rust_counter --release'
    Updating crates.io index
  Downloaded thiserror v1.0.25
  Downloaded libc v0.2.95
  ...
  Compiling ic-cdk v0.3
  Compiling ic-cdk-macros v0.3
  Compiling rust_counter v0.1.0 (/Users/lisagunn/CDK-RS-APR-2021/rust_counter/src/rust_counter)
    Finished release [optimized] target(s) in 1m 10s
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "ryjl3-tyaaa-aaaaa-aaaba-cai"
Installing code for canister rust_counter, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
Deployed canisters.
....

== Dapp のテスト

ローカルでデプロイした Dapp を、以下の内容をテストします:

* `+get+` 関数を呼び、カウンターの値をクエリする。
* `+increment+` 関数を呼び、呼ぶたびにカウンターの値をインクリメントする。
* `+set+` 関数を呼び、引数として与えた任意の値でカウンターの値をアップデートする。

Dapp のテストのために、以下を実行します:

[arabic]
. 以下のコマンドで `+get+` 関数を呼び、`+COUNTER+` 変数の現在の値を取得します；
+
[source,bash]
----
dfx canister call rust_counter get
----
+
このコマンドは、`+COUNTER+` 変数の現在の値である０を返します。
+
....
(0)
....
[arabic]
. `+increment+` 関数を呼び、`+COUNTER+` 変数の値を１つずつインクリメントします：
+
[source,bash]
----
dfx canister call rust_counter increment
----
+
このコマンドは変数の値（ステート）をインクリメントしますが、返し値はありません：
. `+get+` 関数を呼ぶコマンドを再度実行し、`+COUNTER+` 変数の現在の値を確認します。
+
[source,bash]
----
dfx canister call rust_counter get
----
+
このコマンドは、更新された `+COUNTER+` 変数の値である１を返します：
+
....
(1)
....
. 追加のコマンドを実行して、別の値を使った関数の呼び出しを試してみましょう。
+
例えば、以下のようなコマンドを実行して、カウンターの値のセットや取得を試してみましょう：
+
[source,bash]
----
dfx canister call rust_counter set '(987)'
dfx canister call rust_counter get
----
+
このコマンドは、現在の値である 987 を返します。
+
[source,bash]
----
dfx canister call rust_counter increment
dfx canister call rust_counter get
----
+
このコマンドは、インクリメントされた値である 988 を返します。

== {LEE} を止める

アプリケーションのテストをした後は、{LEE} がバックグラウンドで稼働し続けないように、以下の手順で停止します：

. ネットワークの稼働状況が表示されている端末で、Control-C を押して {LEE} を止めてください。


. 以下のコマンドを用いて {LEE} を停止してください：
+
[source,bash]
----
dfx stop
----

////
= Incrementing a counter
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc:
:toc: right
:toc-title: TUTORIAL - SIMPLE PERSISTENCE
:toclevels: 3
:proglang: Rust
:platform: Internet Computer platform
:LEE: local canister execution environment
:IC: Internet Computer blockchain
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:cdk-short-name: DFINITY Rust CDK
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust

In this tutorial, you are going to write a dapp that provides a few basic functions to increment a counter and illustrates the persistence of a value.

For this tutorial, the dapp declares a `+COUNTER+` as a mutable variable to contain a natural number that represents the current value of the counter.
This dapp supports the following functions:

* The `+increment+` function updates the current value, incrementing by 1 with no return value.
* The `+get+` function is a simple query that returns the current value of the counter.
* The `+set+` function updates the current value to the numeric value you specify as an argument.

This tutorial provides a simple example of how you can increment a counter by calling functions on a deployed canister smart contract.
By calling the function to increment a value multiple times, you can verify that the variable state—that is, the value of the variable between calls—persists.

Like the other sample dapps, this tutorial demonstrates a simple, but realistic, workflow in which you perform the following steps:

* Create a new project.
* Write a dapp that compiles into a WebAssembly module.
* Deploy the canister on the {LEE}.
* Invoke the canister smart contract methods to increment then read the value of a counter.

[[before-you-begin]]
== Before you begin

Before you start your project, verify the following:

* You have an internet connection and access to a shell terminal on your local macOS or Linux computer.

* You have downloaded and installed the Rust programming language and Cargo as described in the link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust installation instructions] for your operating system.

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
The Rust tool chain must be at version 1.46.0, or later.

* You have downloaded and installed the {sdk-long-name} package as described in link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].

* You have `+cmake+` installed. For example, use Homebrew with the following command:
+
[source,bash]
----
brew install cmake
----
For instructions on how to install Homebrew, see the link:https://docs.brew.sh/Installation[Homebrew Documentation].

* You have stopped any {LEE} processes running on your computer.

If you aren’t sure how to open a new terminal shell on your local computer, run commands in a terminal, or how to check for and install packages, see link:../quickstart/newcomers{outfilesuffix}[Preliminary steps for newcomers].
If you are comfortable meeting the prerequisites without instructions, continue to <<Create a new project,Create a new project>>.

This tutorial takes approximately 20 minutes to complete.

== Create a new project

To create a new project directory for this tutorial:

[arabic]
. Open a terminal shell on your local computer, if you don’t already have one open.
. Create a new project by running the following command:
+
[source,bash]
----
dfx new rust_counter
----
+
. Change to your project directory by running the following command:
+
[source,bash]
----
cd rust_counter
----

== Modify the default configuration

In the link:rust-quickstart{outfilesuffix}[Hello, World! Rust CDK Quick Start], you saw that creating a new project adds several template files to your project directory much like when you create a new Rust package using the `+cargo new+` command.
You need to modify these default files and add some Rust-specific files to your project before you can build canister smart contracts that run on the {IC}.

To modify the default configuration for a {proglang} project, you'll need to complete the following steps:

* <<Edit the default canister settings>>
* <<Add a Cargo.toml file to the project>>
* <<Add Rust files to the source directory>>
* <<Replace the default dapp>>

=== Edit the default canister settings

One of the template files included in your project directory is a default `+dfx.json+` configuration file.
This file contains settings required to build a project for the {IC} much like the `+Cargo.toml+` file provides build and package management configuration details for Rust programs.
You need to modify the default settings in the `+dfx.json+` configuration file to build Rust dapps that run on the {IC} as canister smart contracts.

To modify the `+dfx.json+` configuration file:

. Check that you are still in the root directory for your project, if needed.
. Open the `+dfx.json+` configuration file in a text editor.
. Replace the `+canisters.rust_counter+` settings with settings for building a canister using the `+cargo build+` command.
+
For example, under the `+rust_counter+` key, replace the `+main+` and `+type+` settings with settings like these:
+
[source,json]
----
  "rust_counter": {
    "build": "cargo build --target wasm32-unknown-unknown --package  rust_counter --release",
    "candid": "src/rust_counter/counter.did",
    "wasm": "target/wasm32-unknown-unknown/release/rust_counter.wasm",
    "type": "custom"
    }
----
. Remove all of the `+rust_counter_assets+` configuration settings from the file.
+
The sample dapp for this tutorial doesn't use any front-end assets, so you can remove those settings from the configuration file.
. Remove the `+defaults+` and `+dfx+` version settings because this tutorial doesn't use these settings.
+
For example, the configuration file looks like this after you modify the settings:
+
....
include::example$counter-tutorial/rust_counter_dfx.json[]
....
. Save your change and close the `+dfx.json+` file to continue.

=== Add a Cargo.toml file to the project

Because we are creating this new Rust project for the {IC} using the {sdk-short-name}, you need to manually create some Rust-specific files in specific locations within the project directory.
Let's start by creating the `+Cargo.toml+` configuration file that describes the packages in our project.

To add a `+Cargo.toml+` configuration file for the project:

. Check that you are still in the root directory for your project, if needed.
. Create a new file in the current directory named `+Cargo.toml+`.
. Open the `+Cargo.toml+` in a text editor.
. Use the `+[workspace]+` key to specify the source file directory for your dapp.
+
For example:
+
[source,toml]
----
[workspace]
members = [
    "src/rust_counter",
]
----
. Save your changes and close the file to continue.

=== Add Rust files to the source directory

Creating a new project creates a default `+src/rust_counter+` directory with a template `+main.mo+`. We'll replace this default dapp with a Rust library `+lib.rs+` package and `+Cargo.toml+` files.

To prepare the source directory with Rust files:

. Check that you are in the root directory for your project, if needed.
. Create a new cargo package using a library template by running the following command:
+
[source, bash]
----
cargo init --lib src/rust_counter
----
+
This command creates a `+src/rust_counter/src+` directory with a library (`+lib.rs+`) package and a `+Cargo.toml+` file in the `+src/rust_counter+` directory.
. Open the `+src/rust_counter/Cargo.toml+` file in a text editor.
+
You use this file to configure the details used to build the Rust package.
+
At a minimum, you need to configure the following sections with basic information about the package name, the crate type, and the version of the {cdk-short-name} libraries to use.
+
--
* `+[package]+`
* `+[lib]+`
* `+[dependencies]+`
--
. Delete the existing `+[dependencies]+` section and replace it with the following:
+
[source,toml]
----
[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
----
+
NOTE: When you deploy the app later in the tutorial, you might get an error message that the dependency version is wrong. If there is a newer version of the {cdk-short-name}, update the dependencies in the `+src/rust_counter/Cargo.toml+` file to match the latest version.
. Save your changes and close the file to continue.

=== Replace the default dapp

Now that you have the files in place for your Rust dapp, we can replace the template `+main.mo+` dapp with the Rust dapp we want to deploy on the {IC}.

To replace the default dapp:

. Check that you are still in the root directory for your project, if needed.
. Delete the template `+src/rust_counter/main.mo+` file by running the following command:
+
[source,bash]
----
rm src/rust_counter/main.mo
----
. Open the template `+src/rust_counter/src/lib.rs+` file in a text editor and delete the existing content.
+
The next step is to write a Rust dapp that declares the `+COUNTER+` variable and implements the `+increment+`, `+get+`, and `+set+` functions.
. Copy and paste the following sample code into the `+lib.rs+` file:
+
[source,motoko]
----
include::example$counter-tutorial/counter.rs[]
----
. Save your changes and close the `+counter.rs+` file to continue.

== Add an interface description file

Candid is an interface description language (IDL) for interacting with canisters running on the Internet Computer.
Candid files provide a language-independent description of a canister's interfaces including the names, parameters, and result formats and data types for each function a canister defines.

By adding Candid files to your project, you can ensure that data is properly converted from its definition in Rust to run safely on the {IC}.

To see details about the Candid interface description language syntax, see the link:../candid-guide/candid-intro{outfilesuffix}[_Candid Guide_] or the https://docs.rs/candid/[Candid crate documentation].

To add a Candid file for this tutorial:

. Check that you are still in the root directory for your project, if needed.
. Create a new file named `+counter.did+` in the `+src/rust_counter/src+` directory.
. Open the `+src/rust_counter/src/counter.did+` file in a text editor, then copy and paste the following `+service+` definition for the `+increment+`, `+get+`, and `+set+` functions:
+
[source,did]
----
service : {
  "increment": () -> ();
  "get": () -> (nat) query;
  "set": (nat) -> ();
}
----
. Save your changes and close the `+counter.did+` file to continue.

== Start the {LEE}

Before you can build the `+rust_counter+` project, you need to connect to the {LEE} running in your development environment or the decentralized {IC} mainnet.

To start the {LEE}:

. Check that you are still in the root directory for your project, if needed.
. Start the {LEE} on your computer in the background by running the following command:
+
[source,bash]
----
dfx start --background
----
+
Depending on your platform and local security settings, you might see a warning displayed.
If you are prompted to allow or deny incoming network connections, click *Allow*.

== Register, build, and deploy your project

After you connect to the {LEE} running in your development environment, you can register, build, and deploy your project locally.

To register, build, and deploy:

. Check that you are still in root directory for your project directory, if needed.
. Register, build, and deploy the canisters specified in the `+dfx.json+` file by running the following command:
+
[source,bash]
----
dfx deploy
----
+
The `+dfx deploy+` command output displays information about each of the operations it performs similar to the following excerpt:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "pubs_user_id" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_counter"...
"rust_counter" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Building canisters...
Executing 'cargo build --target wasm32-unknown-unknown --package  rust_counter --release'
    Updating crates.io index
  Downloaded thiserror v1.0.25
  Downloaded libc v0.2.95
  ...
  Compiling ic-cdk v0.3
  Compiling ic-cdk-macros v0.3
  Compiling rust_counter v0.1.0 (/Users/lisagunn/CDK-RS-APR-2021/rust_counter/src/rust_counter)
    Finished release [optimized] target(s) in 1m 10s
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "ryjl3-tyaaa-aaaaa-aaaba-cai"
Installing code for canister rust_counter, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
Deployed canisters.
....

== Call functions and test the dapp

After successfully deploying the canister, you can test the canister by invoking the functions it provides.
For this tutorial:

* Call the `+get+` function to query the value of the counter.
* Call the `+increment+` function to increment the counter each time it is called.
* Call the `+set+` function to pass an argument to update the counter to an arbitrary value you specify.

To test the dapp:

[arabic]
. Call the `+get+` function to read the current value of the `+COUNTER+` variable by running the following command:
+
[source,bash]
----
dfx canister call rust_counter get
----
+
The command returns the current value of the `+COUNTER+` variable as zero:
+
....
(0)
....
[arabic]
. Call the `+increment+` function to increment the value of the `+COUNTER+` variable by one:
+
[source,bash]
----
dfx canister call rust_counter increment
----
+
This command increments the value of the variable—changing its state—but does not return the result.
. Rerun the command to call the `+get+` function to see the current value of the `+COUNTER+` variable:
+
[source,bash]
----
dfx canister call rust_counter get
----
+
The command returns the updated value of the `+COUNTER+` variable as one:
+
....
(1)
....
. Run additional commands to experiment with call the functions and using different values.
+
For example, try commands similar to the following to set and return the counter value:
+
[source,bash]
----
dfx canister call rust_counter set '(987)'
dfx canister call rust_counter get
----
+
Returns the current value of 987.
+
[source,bash]
----
dfx canister call rust_counter increment
dfx canister call rust_counter get
----
+
Returns the incremented value of 988.

== Stop the {LEE}

After you finish experimenting with your dapp, you can stop the local Internet Computer network so that it doesn’t continue running in the background.

To stop the {LEE}:

. In the terminal that displays network operations, press Control-C to interrupt the {LEE} process.

. Stop the {LEE} by running the following command:
+
[source,bash]
----
dfx stop
----
////