= シンプルなレコードの追加と検索
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc-title: TUTORIAL - SAMPLE PROFILE
:proglang: Rust
:platform: Internet Computer プラットフォーム
:LEE: ローカル実行環境
:IC: Internet Computer ブロックチェーン
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:cdk-short-name: DFINITY Rust CDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust

このチュートリアルでは、名前・説明・キーワードの配列で構成される、シンプルなプロフィールレコードを追加・取得するためのいくつかの基本的な関数を有する Dapp を書きます。

このプログラムは、以下の関数を有します：

* `+update+` 関数は、`+name+`、`+description+`、`+keywords+` からなるプロフィールを追加することができます。
* `+getSelf+` 関数は、関数の呼び出し元に関連づけられたプリンシパルのプロフィールを返します。
* `+get+` 関数は、渡された `+name+` の値にマッチするプロフィールを返す単純なクエリ関数です。
この関数では、指定された名前が `+name+` フィールドと完全に一致する必要があります。
* `+search+` 関数は、より複雑なクエリを実行して、任意のフィールドで指定されたテキストのすべてまたは一部に一致するプロフィールを返します。例えば、特定のキーワードを含むプロフィールや、名前や説明の一部のみにマッチするプロフィールを返すことができます。

このチュートリアルでは、Rust CDK のインターフェースとマクロを使用して、Rust で {IC} 用の Dapps を簡単に書けるようにするための簡単な例を紹介しています。

このチュートリアルでは以下を説明します：

* Candid インターフェース記述言語を使った、少し複雑なデータ（`+record+` とキーワードの `+array+`）の表現の仕方。
* 部分一致する文字列を照合するシンプルな検索機能の書き方。
* 特定のプリンシパルとプロフィールの関連付け方。

[[Before-you-begin]]
== はじめる前に

プロジェクトをはじめる前に、以下をご確認ください:

* インターネットに接続しており、ローカルの macOS または Linux コンピュータでターミナルにアクセスできること。

* link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust のインストール方法] にあるように、Rust プログラミング言語と Cargo が OS にダウンロードされ、インストールされていること。

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
Rust のバージョンは 1.46.0 より新しい必要があります。

* link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[ダウンロードとインストール]の説明に従って、{sdk-long-name} パッケージのダウンロードとインストールが済んでいること。

* `+cmake+` のインストールが済んでいること。例えば、macOS では Homebrew を使って以下のコマンドを実行します:
+
[source,bash]
----
brew install cmake
----
Homebrew をインストールする方法については、link:https://docs.brew.sh/Installation[Homebrew のドキュメント]を参照してください。

* コンピュータ上の {LEE} プロセスが停止していること。

ローカルコンピュータ上で新たなターミナルを開く方法や、ターミナルでコマンドを実行する方法や、インストールパッケージを確認する方法がわからない場合には、link:../quickstart/newcomers{outfilesuffix}[初めての人のための準備]を参照してください。
既に必要な前提条件を満たしている場合には、<<create-a-new-project,新しいプロジェクトの作成>> へと進んでください。

このチュートリアルは、完走に約 20 分かかります。

[[create-a-new-project]]
== 新しいプロジェクトの作成

新しいプロジェクトを作る手順は以下になります:

[arabic]
. ローカル PC でターミナルを開きます。
. 以下のコマンドを実行して新しいプロジェクトを作成します。
+
[source,bash]
----
dfx new --type=rust rust_profile
----
. 以下のコマンドで、プロジェクトディレクトリに移動します。
+
[source,bash]
----
cd rust_profile
----

[[Modify-the-default-project]]
== デフォルトプロジェクトの変更

link:rust-quickstart{outfilesuffix}[Hello World! Rust CDK クイックスタート]では、Rust Canister のデフォルトプロジェクトのファイルを確認しました。

このチュートリアルを完了するには、以下の手順を踏みます。

* <<Replace-the-default-dapp, デフォルト Dapp の置き換え>>
* <<Update-interface-description-file, インターフェース記述ファイルの更新>>

[[Replace-the-default-dapp]]
=== デフォルト Dapp の置き換え

Rust Dapp 用のファイルが揃ったので、テンプレートの `+lib.rs+` Dapp を {IC} にデプロイしたい Rust Dapp に置き換えていきます。

デフォルトのプログラムを置き換えるには、以下のようにします。

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. テキストエディタで `+src/rust_profile/Cargo.toml+` ファイルを開き、依存関係に `+serde+` を追加します。
+
[source,toml]
----
[dependencies]
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
serde = "1.0"
----
+
. `+src/rust_profile/lib.rs+` ファイルをテキストエディタで開き、既存の内容を削除します。
+
次に、`+getSelf+`、`+update+`、`+get+`、`+search+` 関数を Rust プログラムで実装していきます。
. 下のサンプルコードを `+profile.rs+` にコピー＆ペーストしてください。

+
[source,motoko]
----
include::example$profile-tutorial/profile.rs[]
----
. 変更を保存してファイルを閉じ、次に進みます。

[[Update-interface-description-file]]
== インターフェイス記述ファイルの更新

Candid は、{IC} で動作する Canister と対話するためのインターフェース記述言語（IDL）です。
Candid ファイルは、Canister が定義する各関数の名前・引数・返し値のフォーマットやデータ型など、Canister のインターフェースを言語に依存しないように記述したものです。

Candid ファイルをプロジェクトに追加することで、Rust で定義されたデータが {IC} 上で安全に実行されるために適切に変換されることを保証します。

Candid インターフェース記述言語の構文の詳細は link:../candid-guide/candid-intro{outfilesuffix}[_Candid ガイド_]か https://docs.rs/candid/[Candid クレートのドキュメント]をご覧ください。

Candid ファイルを更新するには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. `+src/rust_profile/rust_profile.did+` ファイルをテキストエディタで開いてください。
. `+getSelf+`、`+update+`、`+get+`、`+search+` 関数のために以下の `+service+` の定義をコピー＆ペーストして書き込んでください：
+
[source,did]
----
include::example$profile-tutorial/profile.did[]
----
. 変更を保存してファイルを閉じ、次に進んでください。

[[start-the-local-network]]
== {LEE} を立ち上げる

`+rust_profile+` プロジェクトをビルドする前に、{LEE} か、{IC} メインネットに接続する必要があります。

{LEE} を立ち上げるには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. {LEE} をバックグラウンドで立ち上げるために、以下のコマンドを実行します:
+
[source,bash]
----
dfx start --background --clean
----
+
プラットフォームやローカルのセキュリティ設定によっては、警告が表示される場合があります。
ネットワーク接続を許可するかどうかの確認画面が表示された場合は、*Allow* をクリックします。

[[register-ids]]
== プロジェクトの登録・ビルド・デプロイ

開発環境で立ち上がっている {LEE} に接続した後に、プロジェクトの登録・ビルド・デプロイをローカル環境で行うことができます。

登録・ビルド・デプロイを行うためには、以下のようにします:

. プロジェクトのルートディレクトリにいることを確認します。
. `+dfx.json+` に指定されている Canister を以下のコマンドで、登録・ビルド・デプロイします:
+
[source,bash]
----
dfx deploy
----
+
`+dfx deploy+` コマンドを実行すると、以下のような実行結果に関しての情報が表示されます。
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_profile"...
"rust_profile" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "rust_profile_assets"...
"rust_profile_assets" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Executing: "cargo" "build" "--target" "wasm32-unknown-unknown" "--release" "-p" "rust_profile"
...
    Finished release [optimized] target(s) in 6.31s
Building frontend...
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "r7inp-6aaaa-aaaaa-aaabq-cai"
Installing code for canister rust_profile, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
...
Deployed canisters.
....

[[Call-functions-on-the-deployed-canister]]
== デプロイした Canister の関数を呼ぶ

Canister のデプロイが成功すると、Canister の関数を呼ぶことでテストできるようになります。

このチュートリアルでは、以下のようにします：

* `+update+` 関数を呼び、プロフィールを追加する。
* `+getSelf+` 関数を呼び、プリンシパル ID のプロフィールを表示する。
* `+search+` 関数を呼び、キーワードを使ってプロフィールを検索する。

デプロイした Canister をテストするために：

. `+update+` 関数を呼び、プロフィールレコードを作成するには以下のコマンドを実行します：
+
[source,bash]
----
dfx canister call rust_profile update '(record {name = "Luxi"; description = "mountain dog"; keywords = vec {"scars"; "toast"}})'
----
. `+getSelf+` 関数を呼び、プロフィールレコードを取得するには以下のコマンドを実行します：
+
[source,bash]
----
dfx canister call rust_profile getSelf
----
+
このコマンドは、`+update+` 関数を使って追加したプロフィールを返します。
例えば、以下のようになります：
+
....
(  record {
    name = "Luxi";
    description = "mountain dog";
    keywords = vec { "scars"; "toast" };
  },
)
....
+
いまのところ、この Dapp は１つのプロフィールを保存して返すだけです。
次のコマンドを実行して、`+update+` 関数を使って２つ目のプロフィールを追加すると、`+Luxi+` のプロフィールが `+Dupree+` のプロフィールに置き換わります：
+
[source,bash]
----
dfx canister call rust_profile update '(record {name = "Dupree"; description = "black dog"; keywords = vec {"funny tail"; "white nose"}})'
----
+
`+get+`、`+getSelf+`、`+search+` 関数を使っても、`+Dupree+` のプロフィールが返ってくるだけです。
. `+search+` 関数を以下のように実行してみましょう。
+
[source,bash]
----
dfx canister call rust_profile search '("black")';
----
+
このコマンドは `+description+` との一致を見つけ、以下のプロフィールを返します：
+
....
(
  opt record {
    name = "Dupree";
    description = "black dog";
    keywords = vec { "funny tail"; "white nose" };
  },
....

[[Adding-profiles-for-new-identities]]
== 新しい ID に対するプロフィールの追加

いまのところ、この Dapp はコマンドを実行したプリンシパルに関連付けられた１つのプロフィールしか保存しません。
関数 `+get+`, `+getSelf+`, `+search+` が思った通りに動作することをテストするために、異なるプロフィールを持つことができる新しい ID を追加する必要があります。

テストのために ID を追加します：

. 以下のコマンドで新しいユーザー ID を作成します。
+
[source,bash]
----
dfx identity new Miles
----
+
....
Creating identity: "Miles".
Created identity: "Miles".
....

. `+update+` 関数を呼び、新しい ID に対応したプロフィールを追加します。
+
[source,bash]
----
dfx --identity Miles canister call rust_profile update '(record {name = "Miles"; description = "Great Dane"; keywords = vec {"Boston"; "mantle"; "three-legged"}})'
----
. `+getSelf+` 関数を呼び、`+default+` のユーザー ID に紐づけられたプロフィールを確認します。
+
[source,bash]
----
dfx canister call rust_profile getSelf
----
+
このコマンドはデフォルトの ID に現在紐づけられているプロフィールを表示ます。この例では、Dupree のプロフィールです：
+
....
(
  record {
    name = "Dupree";
    description = "black dog";
    keywords = vec { "funny tail"; "white nose" };
  },
)
....
. `+Miles+` のユーザー ID を使って `+getSelf+` 関数を呼ぶには以下のコマンドを実行します：
+
[source,bash]
----
dfx --identity Miles canister call rust_profile getSelf
----
+
このコマンドは Miles の ID に現在紐づいているプロフィールを表示します。この例では、以下のようになります：
+
....
(
  record {
    name = "Miles";
    description = "Great Dane";
    keywords = vec { "Boston"; "mantle"; "three-legged" };
  },
)
....
. 正しいプロフィールが返されるかどうかをテストするために、説明の一部やキーワードを使って `+search+` 関数を呼び出しましょう。
+
例えば、`+Miles+` のプロフィールが返されることを検証するために、以下のコマンドを実行します：
+
[source,bash]
----
dfx canister call rust_profile search '("Great")'
----
+
このコマンドは `+Miles+` のプロフィールを返します：
+
....
(
  opt record {
    name = "Miles";
    description = "Great Dane";
    keywords = vec { "Boston"; "mantle"; "three-legged" };
  },
)
....
. 正しいプロフィールが返されるかどうかをさらにテストするために、`+search+` 関数を呼びます。
+
例えば、`+Dupree+` のプロフィールが返されることを検証するために、以下のコマンドを実行します：
+
[source,bash]
----
dfx canister call rust_profile search '("black")'
----
+
このコマンドは `+Dupree+` のプロフィールを返します：
+
....
(
  opt record {
    name = "Dupree";
    description = "black dog";
    keywords = vec { "funny tail"; "white nose" };
  },
)
....

[[Extending-the-sample-dapp]]
== サンプル Dapp の拡張

このサンプル Dapp は、ユーザー ID ごとに１つのプロフィールを保存するだけです。
もし各ユーザーのプロフィールにソーシャルコネクションへのリンクを追加するような拡張を行えば、LinkedUp サンプルアプリケーションを Rust で再現することができるでしょう。

[[Stop-the-LEE]]
== {LEE} を止める

アプリケーションのテストをした後は、{LEE} がバックグラウンドで稼働し続けないように、以下の手順で停止します：

. ネットワークの稼働状況が表示されている端末で、Control-C を押して {LEE} のプロセスを止めてください。

. 以下のコマンドを用いて {LEE} を停止してください：
+
[source,bash]
----
dfx stop
----

////
= Adding and searching simple records
ifdef::env-github,env-browser[:outfilesuffix:.adoc]
:toc-title: TUTORIAL - SAMPLE PROFILE
:proglang: Rust
:platform: Internet Computer platform
:LEE: local execution environment
:IC: Internet Computer blockchain
:company-id: DFINITY
:sdk-short-name: DFINITY Canister SDK
:cdk-short-name: DFINITY Rust CDK
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust

In this tutorial, you are going to write a dapp that provides a few basic functions to add and retrieve simple profile records that consist of a name, description, and an array of keywords.

This program supports the following functions:

* The `+update+` function enables you to add a profile that consists of a `+name+`, a `+description+`, and `+keywords+`.
* The `+getSelf+` function returns the profile for the principal associated with the function caller.
* The `+get+` function performs a simple query to return the profile matching the `+name+` value passed to it.
For this function, the name specified must match the `+name+` field exactly to return the record.
* The `+search+` function performs a more complex query to return the profile matching all or part of the text specified in any profile field. For example, the `+search+` function can return a profile containing a specific keyword or that matches only part of a name or description.

This tutorial provides a simple example of how you can use the Rust CDK interfaces and macros to simplify writing dapps in Rust for the {IC}.

This tutorial demonstrates:
* How to represent slightly more complex data—in the form of a profile as a `+record+` and an `+array+` of keywords—using the Candid interface description language.
* How to write a simple search function with partial string matching.
* How profiles are associated with a specific principal.

== Before you begin

Before you start your project, verify the following:

* You have an internet connection and access to a shell terminal on your local macOS or Linux computer.

* You have downloaded and installed the Rust programming language and Cargo as described in the link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust installation instructions] for your operating system.

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
The Rust tool chain must be at version 1.46.0, or later.

* You have downloaded and installed the {sdk-long-name} package as described in link:../../quickstart/quickstart{outfilesuffix}#download-and-install[Download and install].

* You have `+cmake+` installed. For example, use Homebrew with the following command:
+
[source,bash]
----
brew install cmake
----
For instructions on how to install Homebrew, see the link:https://docs.brew.sh/Installation[Homebrew Documentation].

* You have stopped any {LEE} processes running on your computer.

If you aren’t sure how to open a new terminal shell on your local computer, run commands in a terminal, or how to check for and install packages, see link:../quickstart/newcomers{outfilesuffix}[Preliminary steps for newcomers].
If you are comfortable meeting the prerequisites without instructions, continue to <<Create a new project,Create a new project>>.

This tutorial takes approximately 20 minutes to complete.

== Create a new project

To create a new project directory for this tutorial:

[arabic]
. Open a terminal shell on your local computer, if you don’t already have one open.
. Create a new project by running the following command:
+
[source,bash]
----
dfx new --type=rust rust_profile
----
. Change to your project directory by running the following command:
+
[source,bash]
----
cd rust_profile
----

== Modify the default project

In the link:rust-quickstart{outfilesuffix}[Hello, World! Rust CDK Quick Start], you went through the files in a default project with Rust type canister.

To complete this tutorial, you'll need to complete the following steps:

* <<Replace the default dapp>>
* <<Update interface description file>>

=== Replace the default dapp

Now that you have the files in place for your Rust dapp, we can replace the template `+lib.rs+` dapp with the Rust dapp we want to deploy on the {IC}.

To replace the default program:

. Check that you are still in the root directory for your project, if needed.
. Open the `+src/rust_profile/Cargo.toml+` file in a text editor and add `+serde+`  to dependencies.
+
[source,toml]
----
[dependencies]
ic-cdk = "0.4"
ic-cdk-macros = "0.4"
serde = "1.0"
----
+
. Open the template `+src/rust_profile/lib.rs+` file in a text editor and delete the existing content.
+
The next step is to add a Rust program that implements the `+getSelf+`, `+update+`, `+get+`, and `+search+` functions.
. Copy and paste the following sample code into the `+profile.rs+` file:
+
[source,motoko]
----
include::example$profile-tutorial/profile.rs[]
----
. Save your changes and close the file to continue.

== Update interface description file

Candid is an interface description language (IDL) for interacting with canister smart contracts running on the Internet Computer.
Candid files provide a language-independent description of a canister smart contract's interfaces including the names, parameters, and result formats and data types for each function a canister defines.

By adding Candid files to your project, you can ensure that data is properly converted from its definition in Rust to run safely on the {IC}.

To see details about the Candid interface description language syntax, see the link:../candid-guide/candid-intro{outfilesuffix}[_Candid Guide_] or the https://docs.rs/candid/[Candid crate documentation].

To update Candid file for this tutorial:

. Check that you are still in the root directory for your project, if needed.
. Open the `+src/rust_profile/rust_profile.did+`file in a text editor.
. Copy and paste the following `+type+` declaration and `+service+` definition for the `+getSelf+`, `+update+`, `+get+`, and `+search+` functions:
+
[source,did]
----
include::example$profile-tutorial/profile.did[]
----
. Save your changes and close the file to continue.

== Start the {LEE}

Before you can build the `+rust_profile+` project, you need to connect to the {LEE} running in your development environment or the decentralized {IC} mainnet.

To start {LEE}:

. Check that you are still in the root directory for your project, if needed.
. Start the {LEE} on your computer in the background by running the following command:
+
[source,bash]
----
dfx start --background --clean
----
+
Depending on your platform and local security settings, you might see a warning displayed.
If you are prompted to allow or deny incoming network connections, click *Allow*.

== Register, build, and deploy your project

After you connect to the {LEE} running in your development environment, you can register, build, and deploy your project locally.

To register, build, and deploy:

. Check that you are still in root directory for your project directory, if needed.
. Register, build, and deploy the canisters specified in the `+dfx.json+` file by running the following command:
+
[source,bash]
----
dfx deploy
----
+
The `+dfx deploy+` command output displays information about each of the operations it performs similar to the following excerpt:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_profile"...
"rust_profile" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "rust_profile_assets"...
"rust_profile_assets" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Executing: "cargo" "build" "--target" "wasm32-unknown-unknown" "--release" "-p" "rust_profile"
...
    Finished release [optimized] target(s) in 6.31s
Building frontend...
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "r7inp-6aaaa-aaaaa-aaabq-cai"
Installing code for canister rust_profile, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
...
Deployed canisters.
....

== Call functions on the deployed canister

After successfully deploying the canister, you can test the canister by calling the functions it provides.

For this tutorial:

* Call the `+update+` function to add a profile.
* Call the `+getSelf+` function to display the profile for the principal identity.
* Call the `+search+` function to look up the profile using a keyword.

To test the deployed canister:

. Call the `+update+` function to create a profile record by running the following command:
+
[source,bash]
----
dfx canister call rust_profile update '(record {name = "Luxi"; description = "mountain dog"; keywords = vec {"scars"; "toast"}})'
----
. Call the `+getSelf+` function to retrieve a profile record by running the following command:
+
[source,bash]
----
dfx canister call rust_profile getSelf
----
+
The command returns the profile you used the `+update+` function to add.
For example:
+
....
(  record {
    name = "Luxi";
    description = "mountain dog";
    keywords = vec { "scars"; "toast" };
  },
)
....
+
In its current form, the dapp only stores and returns one profile.
If you run the following command to add a second profile using the `+update+` function, the command replaces the `+Luxi+` profile with the `+Dupree+` profile:
+
[source,bash]
----
dfx canister call rust_profile update '(record {name = "Dupree"; description = "black dog"; keywords = vec {"funny tail"; "white nose"}})'
----
+
You can use the `+get+`, `+getSelf+`, and `+search+` functions, but they will only return results for the `+Dupree+` profile.
. Run the following command to call the `+search+` function:
+
[source,bash]
----
dfx canister call rust_profile search '("black")';
----
+
This command finds the matching profile using the `+description+` and returns the profile:
+
....
(
  opt record {
    name = "Dupree";
    description = "black dog";
    keywords = vec { "funny tail"; "white nose" };
  },
....

== Adding profiles for new identities

In its current form, the dapp only stores one profile—the one associated with the principal invoking the commands. To test that the `+get+`, `+getSelf+`, and `+search+` functions do what we want them to, we need to add some new identities that can have different profiles.

To add identities for testing:

. Create a new user identity by running the following command:
+
[source,bash]
----
dfx identity new Miles
----
+
....
Creating identity: "Miles".
Created identity: "Miles".
....

. Call the `+update+` function to add a profile for the new identity.
+
[source,bash]
----
dfx --identity Miles canister call rust_profile update '(record {name = "Miles"; description = "Great Dane"; keywords = vec {"Boston"; "mantle"; "three-legged"}})'
----
. Call the `+getSelf+` function to view the profile associated with the `+default+` user identity.
+
[source,bash]
----
dfx canister call rust_profile getSelf
----
+
The command displays the profile currently associated with the default identity, in this example, the Dupree profile:
+
....
(
  record {
    name = "Dupree";
    description = "black dog";
    keywords = vec { "funny tail"; "white nose" };
  },
)
....
. Call the `+getSelf+` function using the `+Miles+` user identity by running the following command:
+
[source,bash]
----
dfx --identity Miles canister call rust_profile getSelf
----
+
The command displays the profile currently associated with the Miles identity, in this example:
+
....
(
  record {
    name = "Miles";
    description = "Great Dane";
    keywords = vec { "Boston"; "mantle"; "three-legged" };
  },
)
....
. Call the `+search+` function using part of the description or a keyword to further test the whether the correct profile is returned.
+
For example, to verify the `+Miles+` profile is returned, you might run the following command:
+
[source,bash]
----
dfx canister call rust_profile search '("Great")'
----
+
The command returns the `+Miles+` profile:
+
....
(
  opt record {
    name = "Miles";
    description = "Great Dane";
    keywords = vec { "Boston"; "mantle"; "three-legged" };
  },
)
....
. Call the `+search+` function to further test the whether the correct profile is returned.
+
For example, to verify the `+Dupree+` profile is returned, you might run the following command:
+
[source,bash]
----
dfx canister call rust_profile search '("black")'
----
+
The command returns the `+Dupree+` profile:
+
....
(
  opt record {
    name = "Dupree";
    description = "black dog";
    keywords = vec { "funny tail"; "white nose" };
  },
)
....

== Extending the sample dapp

This sample dapp only stores one profile for each unique user identity. If you were to extend this dapp by adding a second method for linking social connections to each users profile, you would be well on your way to recreating the LinkedUp sample application using Rust.

== Stop the {LEE}

After you finish experimenting with your program, you can stop the {LEE} so that it doesn’t continue running in the background.

To stop the {LEE}:

. In the terminal that displays network operations, press Control-C to interrupt the {LEE} process.

. Stop the {LEE} by running the following command:
+
[source,bash]
----
dfx stop
----
////