= Hello World! Rust CDK クイックスタート
:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:toclevels: 3
:proglang: Rust
:platform: Internet Computer platform
:LEE: ローカル実行環境
:IC: Internet Computer blockchain
:company-id: DFINITY
:cdk-short-name: DFINITY Rust CDK
:sdk-short-name: DFINITY Canister SDK
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[quick-start-intro]]
{cdk-long-name} は、分散型の {IC} メインネット上で動作する Dapps を作成するためのツールとサンプルコードとドキュメントを提供しています。
_Hello World! Rust CDK クイックスタート_ では、{cdk-short-name} を初めてインストールすることを想定しています。

初めての方の助けとなるように、このチュートリアルでは、よくある "Hello World" という最初の Dapp を {cdk-short-name} を使うように修正する方法を説明します。
このシンプルな Dapp は、ターミナルにテキストを出力する関数が１つ定義されているだけですが、 {IC} にデプロイする Dapp を Rust で書く際のワークフローを理解するための良いモデルとなります。

[[before-you-begin]]
== はじめる前に

プロジェクトをはじめる前に、以下を確認してください:

* インターネットに接続しており、ローカルの macOS または Linux コンピュータでターミナルにアクセスできること。

* link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust のインストール方法] にあるように、Rust プログラミング言語と Cargo が OS にダウンロードされ、インストールされていること。

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
Rust のバージョンは 1.46.0 より新しい必要があります。

* link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[ダウンロードとインストール]の説明に従って、{sdk-long-name} パッケージのダウンロードとインストールが済んでいること。

* `+cmake+` のインストールが済んでいること。例えば、macOS では Homebrew を使って以下のコマンドを実行します:
+
[source,bash]
----
brew install cmake
----
+
Homebrew をインストールする方法については、link:https://docs.brew.sh/Installation[Homebrew のドキュメント]を参照してください。

* コンピュータ上の {LEE} プロセスが停止していること。

ローカルコンピュータ上で新たなターミナルを開く方法や、ターミナルでコマンドを実行する方法や、インストールパッケージを確認する方法がわからない場合には、link:../quickstart/newcomers{outfilesuffix}[初めての人のための準備]を参照してください。
既に必要な前提条件を満たしている場合には、<<create-a-new-project,新しいプロジェクトの作成>> へと進んでください。

[[create-a-new-project]]
== 新しいプロジェクトの作成

{IC} 用のアプリケーション開発は **プロジェクト** の作成から始まります。
{sdk-short-name} を使用して {IC} の新しいプロジェクトを作成することができます。
{IC} にデプロイするプロジェクトを作成するため、本チュートリアルでは、親コマンドである `+dfx+` とそのサブコマンドを使って Rust プログラムを作成・ビルド・デプロイする方法を中心に説明します。

{sdk-short-name} を使って新しいプロジェクトを作成する手順は以下になります:

. ローカル PC でターミナルを開きます。
. 以下のコマンドを実行し、`+rust_hello+` という名前の Rust Canister を持つ新しいプロジェクトを作成します。
+
[source,bash]
----
dfx new --type=rust rust_hello
----
+
`+dfx new --type=rust rust_hello+` コマンドは `+rust_hello+` プロジェクトのディレクトリとテンプレートファイルと `+rust_hello+` の Git リポジトリを新たに生成します。
. 以下のコマンドで、プロジェクトディレクトリに移動します。
+
[source,bash]
----
cd rust_hello
----

[[Take-a-look-at-the-project]]
== プロジェクトファイルを一通り確認する

プロジェクトをコンパイルし、{IC} にデプロイする準備ができました。
デプロイする前に、プロジェクトファイルを見てみましょう。

=== `+dfx.json+`

プロジェクトディレクトリに含まれるテンプレートファイルの一つに、`+dfx.json+` 設定ファイルがあります。
このファイルには {IC} で動かすプロジェクトをビルドするために必要な設定が含まれています。
これは `+Cargo.toml+` ファイルが Rust プログラムのビルドやパッケージ管理の設定を含んでいるのと同じです。

設定ファイルは次のようなものです。

....
include::example$hello-dfx.json[]
....

`+canisters+` キーの下に、`+rust_hello+` Canister のデフォルト設定があることに注意してください。

. `+"type": "rust "+` は `+rust_hello+` が `+rust+` タイプの Canister であることを指定します。

. `+"candid": "src/rust_hello/rust_hello.did "+` は、Canister に使用する Candid インターフェース記述ファイルの場所を指定します。

. `+"package": "rust_hello "+` は、Rust クレートのパッケージ名を指定します。`+Cargo.toml+` ファイルに記述されているものと同じである必要があります。

=== `+Cargo.toml+`

ルートディレクトリには、`+Cargo.toml+` というファイルがあります。

これは、各 Rust クレートのパスを指定することで、Rust ワークスペースを定義しています。
Rust タイプの Canister は、WebAssembly にコンパイルされた Rust クレートにすぎません。
ここでは、`+src/rust_hello+` に一つのメンバーを持っており、これが唯一の Rust Canister です。

[source,toml]
----
[workspace]
members = [
    "src/rust_hello",
]
----

=== `+src/rust_hello/+`

さて、Rust Canister を見ていきましょう。標準的な Rust クレートと同様に `+Cargo.toml+` ファイルがあり、Rust クレートをビルドするための詳細な設定をしています。

==== `+src/rust_hello/Cargo.toml+`

[source,toml]
----
[package]
name = "rust_hello"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
----

`+crate-type = ["cdylib"]+` の行に注目してください。これは、この Rust プログラムを WebAssembly モジュールにコンパイルするために必要なものです。

==== `+src/rust_hello/lib.rs+`

デフォルトのプロジェクトでは、{cdk-short-name} `+query+` マクロを使用したシンプルな `+greet+` 関数が用意されています。

[source,rust]
----
#[ic_cdk_macros::query]
fn greet(name: String) -> String {
    format!("Hello, {}!", name)
}
----

==== `+src/rust_hello/rust_hello.did+`

Candid は、{IC} で動作する Canister と対話するためのインターフェース記述言語（IDL）です。
Candid ファイルは、Canister が定義する各関数の名前・引数・返し値のフォーマットやデータ型など、Canister のインターフェースを言語に依存しないように記述したものです。

Candid ファイルをプロジェクトに追加することで、Rust で定義されたデータが {IC} 上で安全に実行されるために適切に変換されることを保証します。


Candid インターフェース記述言語の構文の詳細は link:../candid-guide/candid-intro{outfilesuffix}[_Candid ガイド_]か https://docs.rs/candid/[Candid クレートのドキュメント]をご覧ください。

[source,did]
----
service : {
    "greet": (text) -> (text) query;
}
----

これは、`+greet+` 関数が `+text+` データを入力として受け取り `+text+` データを返す `+query+` メソッドであることを指定します。

[[start-the-local-network]]
== {LEE} を立ち上げる

プロジェクトをビルドする前に、{LEE} か、{IC} メインネットに接続する必要があります。

{LEE} を立ち上げるには、以下のようにします:

[arabic]
. 自分がプロジェクトのルートディレクトリにいることを確認します。
. {LEE} をバックグラウンドで立ち上げるために、以下のコマンドを実行します:
+
[source,bash]
----
dfx start --background
----
+
プラットフォームやローカルのセキュリティ設定によっては、警告が表示される場合があります。
ネットワーク接続を許可するかどうかの確認画面が表示された場合は、*Allow* をクリックします。

[[register-ids]]
== プロジェクトの登録・ビルド・デプロイ

開発環境で立ち上がっている {LEE} に接続した後に、プロジェクトの登録・ビルド・デプロイをローカル環境で行うことができます。
登録・ビルド・デプロイを行うためには、以下のようにします:

. プロジェクトのルートディレクトリにいることを確認します。
. 以下のコマンドを実行し、`wasm32-unknown-unknown` がインストールされていることを確認します：
+
[source,bash]
rustup target add wasm32-unknown-unknown
+
. `+dfx.json+` に指定されている Canister を以下のコマンドで、登録・ビルド・デプロイします:
+
[source,bash]
----
dfx deploy
----
+
`+dfx deploy+` コマンドを実行すると、以下のような実行結果に関しての情報が表示されます。
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_hello"...
"rust_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "rust_hello_assets"...
"rust_hello_assets" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Executing: "cargo" "build" "--target" "wasm32-unknown-unknown" "--release" "-p" "rust_hello"
    Updating crates.io index
   Compiling unicode-xid v0.2.2
   ...
Building frontend...
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "r7inp-6aaaa-aaaaa-aaabq-cai"
Installing code for canister rust_hello, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
...
Deployed canisters.
....

[[Test-the-dapp]]
== Dapp のテスト

ローカルでデプロイした Dapp をテストするには、以下のようにします:

. プロジェクトのルートディレクトリにいることを確認します。
. Dpp の `+greet+` 関数を以下のコマンドで呼び出します:
+
[source,bash]
----
dfx canister call rust_hello greet world
----
. rust_hello+` Canister の `+greet+` 関数の呼び出しがテキストメッセージである `+("Hello, world!")+` を返すことを確認します。

[[Stop-the-LEE]]
== {LEE} を止める

アプリケーションのテストをした後は、{LEE} がバックグラウンドで稼働し続けないように、以下の手順で停止します:

. ネットワークの稼働状況が表示されている端末で、Control-C を押して {LEE} を止めてください。

. 以下のコマンドを用いて {LEE} を停止してください:
+
[source,bash]
----
dfx stop
----

////
= Hello, World! Rust CDK Quick Start
:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:toclevels: 3
:proglang: Rust
:platform: Internet Computer platform
:LEE: local execution environment
:IC: Internet Computer blockchain
:company-id: DFINITY
:cdk-short-name: DFINITY Rust CDK
:sdk-short-name: DFINITY Canister SDK
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[quick-start-intro]]
The {cdk-long-name} provides tools, sample code, and documentation to help you create dapps to run on the decentralized {IC} mainnet.
This _Hello, World! Rust CDK Quick Start_ assumes that you are installing the {cdk-short-name} for the first time.

To help you get started, this tutorial illustrates how to modify the traditional "Hello World" first dapp to use the {cdk-short-name}.
This simple dapp has just one function that prints text to a terminal, but it provides a good model for understanding the workflow when writing dapps in Rust that you want to deploy on the {IC}.

[[before-you-begin]]
== Before you begin

Before you start your project, verify the following:

* You have an internet connection and access to a shell terminal on your local macOS or Linux computer.

* You have downloaded and installed the Rust programming language and Cargo as described in the link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust installation instructions] for your operating system.

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
The Rust tool chain must be at version 1.46.0, or later.

* You have downloaded and installed the {sdk-long-name} package as described in link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].

* You have `+cmake+` installed. For example, use Homebrew with the following command:
+
[source,bash]
----
brew install cmake
----
+
For instructions on how to install Homebrew, see the link:https://docs.brew.sh/Installation[Homebrew Documentation].

* You have stopped any {LEE} processes running on your computer.

If you aren’t sure how to open a new terminal shell on your local computer, run commands in a terminal, or how to check for and install packages, see link:../quickstart/newcomers{outfilesuffix}[Preliminary steps for newcomers].
If you are comfortable meeting the prerequisites without instructions, continue to <<Create a new project,Create a new project>>.

[[create-a-new-project]]
== Create a new project

Applications for the {IC} start as **projects**.
You can create new projects for the {IC} using the {sdk-short-name}.
Because you are building this project to be deployed on the {IC}, this tutorial focuses on how to create, build, and deploy a Rust program by using the `+dfx+` parent command and its subcommands.

To create a new project using the {sdk-short-name}:

. Open a terminal shell on your local computer, if you don’t already have one open.
. Create a new project with rust canister named `+rust_hello+` by running the following command:
+
[source,bash]
----
dfx new --type=rust rust_hello
----
+
The `+dfx new --type=rust rust_hello+` command creates a new `+rust_hello+` project directory, template files, and a new `+rust_hello+` Git repository for your project.
. Change to your project directory by running the following command:
+
[source,bash]
----
cd rust_hello
----

== Take a look at the project

The project is ready to be compiled and deployed to the {IC}.
Before that, let's go through the project files.

=== `+dfx.json+`

One of the template files included in your project directory is a default `+dfx.json+` configuration file.
This file contains settings required to build a project for the {IC} much like the `+Cargo.toml+` file provides build and package management configuration details for Rust programs.

The configuration file should look like this:

....
include::example$hello-dfx.json[]
....

Notice that under the `+canisters+` key, you have some default settings for the `+rust_hello+` canister.

. `+"type": "rust"+` specifies that `+rust_hello+` is a `+rust+` type canister.

. `+"candid": "src/rust_hello/rust_hello.did"+` specifies the location of the Candid interface description file to use for the canister.

. `+"package": "rust_hello"+` specifies the package name of the Rust crate. It should be the same as in the crate `+Cargo.toml+` file.

=== `+Cargo.toml+`

In the root directory, there is a `+Cargo.toml+` file.

It defines a Rust workspace by specifying paths to each Rust crate.
A Rust type canister is just a Rust crate compiled to WebAssembly.
Here we have one member at `+src/rust_hello+` which is the only Rust canister.
[source,toml]
----
[workspace]
members = [
    "src/rust_hello",
]
----

=== `+src/rust_hello/+`

Now we are in the Rust canister. As any standard Rust crate, it has a `+Cargo.toml+` file which configures the details to build the Rust crate.

==== `+src/rust_hello/Cargo.toml+`

[source,toml]
----
[package]
name = "rust_hello"
version = "0.1.0"
edition = "2018"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.4"
ic-cdk-macros = "0.4"
----

Notice the `+crate-type = ["cdylib"]+` line which is necessary to compile this rust program into WebAssembly module.

==== `+src/rust_hello/lib.rs+`

The default project has a simple `+greet+` function that uses the {cdk-short-name} `+query+` macro.

[source,rust]
----
#[ic_cdk_macros::query]
fn greet(name: String) -> String {
    format!("Hello, {}!", name)
}
----

==== `+src/rust_hello/rust_hello.did+`

Candid is an interface description language (IDL) for interacting with canisters running on the Internet Computer.
Candid files provide a language-independent description of  a canister's interfaces including the names, parameters, and result formats and data types for each function a canister defines.

By adding Candid files to your project, you can ensure that data is properly converted from its definition in Rust to run safely on the {IC}.

To see details about the Candid interface description language syntax, see the link:../candid-guide/candid-intro{outfilesuffix}[_Candid Guide_] or the https://docs.rs/candid/[Candid crate documentation].

[source,did]
----
service : {
    "greet": (text) -> (text) query;
}
----

This definition specifies that the `+greet+` function is a `+query+` method which takes `+text+` data as input and returns `+text+` data.

[[start-the-local-network]]
== Start the {LEE}

Before you can build your project, you need to connect to the {LEE} running in your development environment or the decentralized {IC} mainnet.

To start the {LEE}:

[arabic]
. Check that you are still in the root directory for your project, if needed.
. Start the {LEE} on your computer in the background by running the following command:
+
[source,bash]
----
dfx start --background
----
+
Depending on your platform and local security settings, you might see a warning displayed.
If you are prompted to allow or deny incoming network connections, click *Allow*.

[[register-ids]]
== Register, build, and deploy your project

After you connect to the {LEE} running in your development environment, you can register, build, and deploy your project locally.

To register, build, and deploy:

. Check that you are still in root directory for your project directory, if needed.
. Make sure you have `wasm32-unknown-unknown` installed by running the command:
+
[source,bash]
rustup target add wasm32-unknown-unknown
+
. Register, build, and deploy the canisters specified in the `+dfx.json+` file by running the following command:
+
[source,bash]
----
dfx deploy
----
+
The `+dfx deploy+` command output displays information about each of the operations it performs similar to the following excerpt:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "default" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_hello"...
"rust_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Creating canister "rust_hello_assets"...
"rust_hello_assets" canister created with canister id: "ryjl3-tyaaa-aaaaa-aaaba-cai"
Building canisters...
Executing: "cargo" "build" "--target" "wasm32-unknown-unknown" "--release" "-p" "rust_hello"
    Updating crates.io index
   Compiling unicode-xid v0.2.2
   ...
Building frontend...
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "r7inp-6aaaa-aaaaa-aaabq-cai"
Installing code for canister rust_hello, with canister_id rrkah-fqaaa-aaaaa-aaaaq-cai
...
Deployed canisters.
....

////
////
== Optimize and test the dapp

At this point, you have a dapp compiled to WebAssembly that has not been optimized for deployment on the {IC}.

To optimize and test the resulting canister:

. Check that you are still in root directory for your project directory, if needed.
. Install the `+ic-cdk-optimizer+` crate by running the following command:
+
[source,bash]
----
cargo install ic-cdk-optimizer
----
+
This package optimizes your Rust code to reduce the size of the WebAssembly output to ensure your dapp can be uploaded as a canister.
. Create a release directory within the `+src/rust_hello+` directory by running the following command:
+
[source,bash]
----
mkdir -p src/rust_hello/target/wasm32-unknown-unknown/release/
----
. Optimize the code within the `+target/rust_hello+` directory by running the following command:
+
[source,bash]
----
ic-cdk-optimizer target/wasm32-unknown-unknown/release/rust_hello.wasm -o target/wasm32-unknown-unknown/release/rust_hello-opt.wasm
----
////
////

== Test the dapp

To test the deployed dapp locally:

. Check that you are still in root directory for your project directory, if needed.
. Call the `+greet+` function in the dapp by running the following command:
+
[source,bash]
----
dfx canister call rust_hello greet world
----
. Verify that the call to the `+rust_hello+` canister `+greet+` function returns a text message `+("Hello, world!")+`.

== Stop the {LEE}

After testing the application, you can stop the {LEE} so that it doesn’t continue running in the background.

To stop the {LEE}:

. In the terminal that displays network operations, press Control-C to interrupt the {LEE} process.

. Stop the {LEE} running on your computer by running the following command:
+
[source,bash]
----
dfx stop
----

////