= Hello World! Rust CDK クイックスタート
:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:toclevels: 3
:proglang: Rust
:platform: Internet Computer platform
:LEE: ローカル実行環境
:IC: Internet Computer blockchain
:company-id: DFINITY
:cdk-short-name: DFINITY Rust CDK
:sdk-short-name: DFINITY Canister SDK
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[quick-start-intro]]
{cdk-long-name} は、分散型の {IC} メインネット上で動作する Dapps を作成するためのツールとサンプルコードとドキュメントを提供しています。
_Hello World! Rust CDK クイックスタート_ では、{cdk-short-name} を初めてインストールすることを想定しています。

初めての方の助けとなるように、このチュートリアルでは、よくある "Hello World" という最初の Dapp を {cdk-short-name} を使うように修正する方法を説明します。
このシンプルな Dapp は、ターミナルにテキストを出力する関数が１つ定義されているだけですが、 {IC} にデプロイする Dapp を Rust で書く際のワークフローを理解するための良いモデルとなります。

[[before-you-begin]]
== はじめる前に

プロジェクトをはじめる前に、以下を確認してください:

* インターネットに接続しており、ローカルの macOS または Linux コンピュータでターミナルにアクセスできること。

* link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust のインストール方法] にあるように、Rust プログラミング言語と Cargo が OS にダウンロードされ、インストールされていること。

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
Rust のバージョンは 1.46.0 より新しい必要があります。

* link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[ダウンロードとインストール]の説明に従って、{sdk-long-name} パッケージのダウンロードとインストールが済んでいること。

* `+cmake+` のインストールが済んでいること。例えば、macOS では Homebrew を使って以下のコマンドを実行します:
+
[source,bash]
----
brew install cmake
----
+
Homebrew をインストールする方法については、link:https://docs.brew.sh/Installation[Homebrew のドキュメント]を参照してください。

* コンピュータ上の {LEE} プロセスが停止していること。

ローカルコンピュータ上で新たなターミナルを開く方法や、ターミナルでコマンドを実行する方法や、インストールパッケージを確認する方法がわからない場合には、link:../quickstart/newcomers{outfilesuffix}[初めての人のための準備]を参照してください。
既に必要な前提条件を満たしている場合には、<<create-a-new-project,新しいプロジェクトの作成>> へと進んでください。

[[create-a-new-project]]
== 新しいプロジェクトの作成

{IC} 用のアプリケーション開発は **プロジェクト** の作成から始まります。
Cargo と {sdk-short-name} のどちらかを使用して {IC} の新しいプロジェクトを作成します。
{IC} にデプロイするプロジェクトを作成するため、本チュートリアルでは、親コマンドである `+dfx+` とそのサブコマンドを使って Rust プログラムを作成・ビルド・デプロイする方法を中心に説明します。
ただし、`+cargo new+` で新規プロジェクトを作成した場合には、開発環境で必要となる `+Cargo.lock+` や `+Cargo.toml+` などのデフォルトファイルがプロジェクトのディレクトリ構造に追加されます。

* プロジェクトの作成に Cargo を使用する場合は、{cdk-long-name} が必要とするファイルをいくつか手動で追加する必要があります。
* プロジェクトの作成に {sdk-short-name} を使用する場合は、Cargo が必要とするファイルをいくつか手動で追加する必要があります。

{sdk-short-name} を使って新しいプロジェクトを作成する手順は以下になります:

. ローカル PC でターミナルを開きます。
. 以下のコマンドを実行し、`+rust_hello+` という名前の新しいプロジェクトを作成します。
+
[source,bash]
----
dfx new rust_hello
----
+
`+dfx new rust_hello+` コマンドは `+rust_hello+` プロジェクトのディレクトリとテンプレートファイルと `+rust_hello+` の Git リポジトリを新たに生成します。
. 以下のコマンドで、プロジェクトディレクトリに移動します。
+
[source,bash]
----
cd rust_hello
----

== デフォルト設定の変更

新しいプロジェクトを作成すると、`+cargo new+` コマンドを使ったときと同じように、いくつかのテンプレートファイルがプロジェクトディレクトリに追加されます。
{IC} 上で動作する Canister スマートコントラクトを構築する前に、いくつか Rust 固有のファイルをプロジェクトに追加する必要があります。

{proglang} プロジェクトのデフォルト設定を変更するには、以下の手順を踏みます。

* <<edit-the-default-canister-settings, Canister の初期設定の変更>>
* <<add-a-cargotoml-file-to-the-project, Cargo.toml ファイルの追加>>
* <<add-Rust-files-to-the-source-directory, src ディレクトリへの Rust ファイルの追加>>
* <<replace-the-default-dapp, デフォルト Dapp の置き換え>>

[[edit-the-default-canister-settings]]
=== Canister の初期設定の変更

プロジェクトディレクトリに含まれるテンプレートファイルの一つに、`+dfx.json+` 設定ファイルがあります。
このファイルには {IC} で動かすプロジェクトをビルドするために必要な設定が含まれています。
これは `+Cargo.toml+` ファイルが Rust プログラムのビルドやパッケージ管理の設定を含んでいるのと同じです。
Canister スマートコントラクトとして Rust の Dapps をビルドするには、`+dfx.json+` のデフォルト設定を変更する必要があります。

`+dfx.json+` を変更するには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. テキストエディタで `+dfx.json+` を開きます。
. `+canisters+` キーの下に、`+rust_hello+` Canister のデフォルト設定があることにお気づきでしょうか。メインの Dapp ファイルへのデフォルトパスや、`type` が `+motoko+` になっていることなどがわかると思います。
. `+canisters.rust_hello.main+` のキーと設定を、 `+canisters.rust_hello.build+` のキーに置き換え、実行する `+cargo build+` コマンドを以下のように指定します:
+
[source, json]
----
"build": "cargo build --target wasm32-unknown-unknown --package rust_hello --release",
----
. `+canisters.rust_hello.candid+` キーを追加し、Canister に使用する Candid インターフェース記述ファイルの場所を以下のように指定します:
+
[source, json]
----
"candid": "src/rust_hello/src/rust_hello.did",
----
. `+canisters.rust_hello.wasm+` のキーを追加し、Canister に使用するコンパイル済みの WebAssembly ファイルの場所を以下のように指定します:
+
[source, json]
----
"wasm": "target/wasm32-unknown-unknown/release/rust_hello.wasm",
----
. `+canisters.rust_hello.type+` のキーを変更し、Canister の `type` として `+custom+` を指定します:
+
[source, json]
----
"type": "custom"
----
. `+rust_hello_assets+` の設定をすべて削除します。
+
このチュートリアルの Dapp では、フロントエンドの `asset` を使用していないので、設定ファイルからこれらの設定を削除することができます。
+
また、このチュートリアルでは `+defaults+` と `+dfx+` のキーも削除することができます。
+
これらの不要な設定を削除した後の設定ファイルは次のようになります:
+
....
include::example$hello-dfx.json[]
....

. 変更内容を保存し、ファイルを閉じて次に進みます。

[[add-a-cargotoml-file-to-the-project]]
=== Cargo.toml ファイルの追加

{IC} で動かすために {sdk-short-name} を使って新しい Rust プロジェクトを作っているので、プロジェクトディレクトリ内の特定の場所に Rust 固有のファイルを手動で作成する必要があります。
まず、プロジェクトのパッケージ情報を書くための `+Cargo.toml+` ファイルを作成しましょう。

プロジェクトに `+Cargo.toml+` ファイルを追加するには、以下のようにします：

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. カレントディレクトリに `+Cargo.toml+` という名前のファイルを作成します.
. エキストエディタで `+Cargo.toml+` を開きます。
. `+[workspace]+` キーを使って Dapp のソースファイルのディレクトリを指定します:
+
[source,toml]
----
[workspace]
members = [
    "src/rust_hello",
]
----
. 変更内容を保存し、ファイルを閉じて次に進みます。

[[add-Rust-files-to-the-source-directory]]
=== src ディレクトリへの Rust ファイルの追加

新しいプロジェクトを作成すると、`+src/rust_hello+` ディレクトリが作成され、テンプレートとして `+main.mo+` が作成されます。
このデフォルトの Dapp を、Rust の `+lib.rs+` パッケージと `+Cargo.toml+` ファイルで置き換えていきます。

`src` ディレクトリに Rust ファイルを用意するのは、以下の手順となります:

. 自分がルートディレクトリにいることを確認します。
. 以下のコマンドを実行して、ライブラリテンプレートを使用した新しい Cargo パッケージを作成します:
+
[source, bash]
----
cargo init --lib src/rust_hello
----
+
このコマンドは `+src/rust_hello/src+` ディレクトリに、ライブラリ(`+lib.rs+`)パッケージと、`+Cargo.toml+` ファイルを作成します。
. `+src/rust_hello/Cargo.toml+` ファイルをテキストエディタで開きます。
+
このファイルを使って、Rustパッケージのビルドに関する詳細を設定します。
+
最小限の構成として、パッケージ名・クレートタイプ・使用する {cdk-short-name} ライブラリのバージョンなどの基本情報を以下のように設定する必要があります:
+
--
* `+[package]+`
* `+[lib]+`
* `+[dependencies]+`
--
. 既存の `+[dependencies]+` セクションを削除して、以下のように置き換えます:
+
[source,toml]
----
[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
----
+
NOTE: このあとのチュートリアルでアプリを実際にデプロイする際に、パッケージの依存関係が間違っているというエラーメッセージが表示されることがあります。もし新しいバージョンの {cdk-short-name} がある場合は、`+src/rust_hello/Cargo.toml+` ファイルの依存関係を最新バージョンに合わせて更新してください。
. 変更を保存してファイルを閉じ、次に進みます。

[[replace-the-default-dapp]]
=== デフォルトの Dapp を置き換え

これで Rust Dapp 用のファイルが揃ったので、`+main.mo+` Dapp を Rust Dapp に置き換えていきます。

既存の Dapp を置き換えるには以下のようにします：

. 自分がルートディレクトリにいることを確認します。
. `+src/rust_hello/main.mo+` ファイルを以下のコマンドによって削除します:
+
[source,bash]
----
rm src/rust_hello/main.mo
----
. `+src/rust_hello/src/lib.rs+` ファイルをテキストエディタで開き、既存の内容を削除します。
. {cdk-short-name} の `+query+` マクロを使った、シンプルな `+print+` 関数を以下のように書いてみましょう:
+
[source,rust]
----
#[ic_cdk_macros::query]
fn print() {
    ic_cdk::print("Hello World from DFINITY!");
}
----
. 変更を保存してファイルを閉じ、次に進みます。

== インターフェイス記述ファイルの追加

Candid は、{IC} で動作する Canister と対話するためのインターフェース記述言語（IDL）です。
Candid ファイルは、Canister が定義する各関数の名前・引数・返し値のフォーマットやデータ型など、Canister のインターフェースを言語に依存しないように記述したものです。

Candid ファイルをプロジェクトに追加することで、Rust で定義されたデータが {IC} 上で安全に実行されるために適切に変換されることを保証します。


Candid インターフェース記述言語の構文の詳細は link:../candid-guide/candid-intro{outfilesuffix}[_Candid ガイド_]か https://docs.rs/candid/[Candid クレートのドキュメント]をご覧ください。

Candid ファイルを追加するには、以下のようにします:

. 自分がプロジェクトのルートディレクトリにいることを確認します。
. `+src/rust_hello/src/+` ディレクトリに、`+rust_hello.did+` という名前でファイルを作成します。
. `+src/rust_hello/src/rust_hello.did+` ファイルをテキストエディタで開きます。
. `+print+` 関数のために、以下のように `+service+` を定義します:
+
[source,did]
----
service : {
    "print": () -> () query;
}
----
+
これは、`+print+` 関数に渡されたデータが、変更されずに `+query+` として返されることを表しています。
. 変更を保存してファイルを閉じ、次に進んでください。

[[start-the-local-network]]
== {LEE} を立ち上げる

プロジェクトをビルドする前に、{LEE} か、{IC} メインネットに接続する必要があります。

{LEE} を立ち上げるには、以下のようにします:

[arabic]
. 自分がプロジェクトのルートディレクトリにいることを確認します。
. {LEE} をバックグラウンドで立ち上げるために、以下のコマンドを実行します:
+
[source,bash]
----
dfx start --background
----
+
プラットフォームやローカルのセキュリティ設定によっては、警告が表示される場合があります。
ネットワーク接続を許可するかどうかの確認画面が表示された場合は、*Allow* をクリックします。

[[register-ids]]
== プロジェクトの登録・ビルド・デプロイ

開発環境で立ち上がっている {LEE} に接続した後に、プロジェクトの登録・ビルド・デプロイをローカル環境で行うことができます。
登録・ビルド・デプロイを行うためには、以下のようにします:

. プロジェクトのルートディレクトリにいることを確認します。
. `+dfx.json+` に指定されている Canister を以下のコマンドで、登録・ビルド・デプロイします:
+
[source,bash]
----
dfx deploy
----
+
`+dfx deploy+` コマンドを実行すると、以下のような実行結果に関しての情報が表示されます。
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "pubs_user_id" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_hello"...
"rust_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Building canisters...
Executing 'cargo build --target wasm32-unknown-unknown --package rust_hello --release'
    Updating crates.io index
   Compiling unicode-xid v0.2.2
   ...
Building canisters...
Executing 'cargo build --target wasm32-unknown-unknown --package rust_hello --release'
   Compiling rust_hello v0.1.0 (/Users/lisagunn/CDK-RS-APR-2021/rust_hello/src/rust_hello)
    Finished release [optimized] target(s) in 1.26s
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "rkp4c-7iaaa-aaaaa-aaaca-cai"
Installing code for canister rust_hello, with canister_id r7inp-6aaaa-aaaaa-aaabq-cai
Deployed canisters.
....

== Dapp のテスト

ローカルでデプロイした Dapp をテストするには、以下のようにします:

. プロジェクトのルートディレクトリにいることを確認します。
. Dpp の `+print+` 関数を以下のコマンドで呼び出します:
+
[source,bash]
----
dfx canister call rust_hello print
----
. `+rust_hello+` Canister の `+print+` 関数を呼び出した結果、以下のように `+Hello World from DFINITY!+` の挨拶が表示されることを確認します:
+
....
[Canister ryjl3-tyaaa-aaaaa-aaaba-cai] Hello World from DFINITY!
()
....

== {LEE} を止める

アプリケーションのテストをした後は、{LEE} がバックグラウンドで稼働し続けないように、以下の手順で停止します:

. ネットワークの稼働状況が表示されている端末で、Control-C を押して {LEE} を止めてください。

. 以下のコマンドを用いて {LEE} を停止してください:
+
[source,bash]
----
dfx stop
----

////
= Hello, World! Rust CDK Quick Start
:experimental:
// Define unicode for Apple Command key.
:commandkey: &#8984;
:toclevels: 3
:proglang: Rust
:platform: Internet Computer platform
:LEE: local execution environment
:IC: Internet Computer blockchain
:company-id: DFINITY
:cdk-short-name: DFINITY Rust CDK
:sdk-short-name: DFINITY Canister SDK
:cdk-long-name: DFINITY Canister Development Kit (CDK) for Rust
:sdk-long-name: DFINITY Canister Software Development Kit (SDK)
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

[[quick-start-intro]]
The {cdk-long-name} provides tools, sample code, and documentation to help you create dapps to run on the decentralized {IC} mainnet.
This _Hello, World! Rust CDK Quick Start_ assumes that you are installing the {cdk-short-name} for the first time.

To help you get started, this tutorial illustrates how to modify the traditional "Hello World" first dapp to use the {cdk-short-name}.
This simple dapp has just one function that prints text to a terminal, but it provides a good model for understanding the workflow when writing dapps in Rust that you want to deploy on the {IC}.

[[before-you-begin]]
== Before you begin

Before you start your project, verify the following:

* You have an internet connection and access to a shell terminal on your local macOS or Linux computer.

* You have downloaded and installed the Rust programming language and Cargo as described in the link:https://doc.rust-lang.org/book/ch01-01-installation.html[Rust installation instructions] for your operating system.

+
[source,bash]
----
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
----
+
The Rust tool chain must be at version 1.46.0, or later.

* You have downloaded and installed the {sdk-long-name} package as described in link:../quickstart/local-quickstart{outfilesuffix}#download-and-install[Download and install].

* You have `+cmake+` installed. For example, use Homebrew with the following command:
+
[source,bash]
----
brew install cmake
----
+
For instructions on how to install Homebrew, see the link:https://docs.brew.sh/Installation[Homebrew Documentation].

* You have stopped any {LEE} processes running on your computer.

If you aren’t sure how to open a new terminal shell on your local computer, run commands in a terminal, or how to check for and install packages, see link:../quickstart/newcomers{outfilesuffix}[Preliminary steps for newcomers].
If you are comfortable meeting the prerequisites without instructions, continue to <<Create a new project,Create a new project>>.

[[create-a-new-project]]
== Create a new project

Applications for the {IC} start as **projects**.
You can create new projects for the {IC} using either Cargo or the {sdk-short-name}.
Because you are building this project to be deployed on the {IC}, this tutorial focuses on how to create, build, and deploy a Rust program by using the `+dfx+` parent command and its subcommands.
However, creating a new project with `+cargo new+` adds some default files to the project directory structure—such as the `+Cargo.lock+` and `+Cargo.toml+` files—that you will need in your development environment.

* If you decide to use Cargo to create your project, you will need to manually add some files that the {cdk-long-name} requires.
* If you decide to use {sdk-short-name} to create your project, you will need to manually add some files that Cargo requires.

To create a new project using the {sdk-short-name}:

. Open a terminal shell on your local computer, if you don’t already have one open.
. Create a new project named `+rust_hello+` by running the following command:
+
[source,bash]
----
dfx new rust_hello
----
+
The `+dfx new rust_hello+` command creates a new `+rust_hello+` project directory, template files, and a new `+rust_hello+` Git repository for your project.
. Change to your project directory by running the following command:
+
[source,bash]
----
cd rust_hello
----

== Modify the default configuration

Creating a new project adds several template files to your project directory much like when you create a new Rust package using the `+cargo new+` command.
You need to modify these default files and add some Rust-specific files to your project before you can build canister smart contracts that run on the {IC}.

To modify the default configuration for a {proglang} project, you'll need to complete the following steps:

* <<Edit the default canister settings>>
* <<Add a Cargo.toml file to the project>>
* <<Add Rust files to the source directory>>
* <<Replace the default dapp>>

=== Edit the default canister settings

One of the template files included in your project directory is a default `+dfx.json+` configuration file.
This file contains settings required to build a project for the {IC} much like the `+Cargo.toml+` file provides build and package management configuration details for Rust programs.
You need to modify the default settings in the `+dfx.json+` configuration file to build Rust dapps that run on the {IC} as canister smart contracts.

To modify the `+dfx.json+` configuration file:

. Check that you are still in the root directory for your project, if needed.
. Open the `+dfx.json+` configuration file in a text editor.
. Notice that under the `+canisters+` key, you have some default settings for the `+rust_hello+` canister such as the default path to the main dapp file and a default type of `+motoko+`.
. Replace the `+canisters.rust_hello.main+` key and setting with a `+canisters.rust_hello.build+` key and specify the `+cargo build+` command to execute.
+
For example:
+
[source, json]
----
"build": "cargo build --target wasm32-unknown-unknown --package rust_hello --release",
----
. Add a `+canisters.rust_hello.candid+` key and specify the location of the Candid interface description file to use for the canister.
+
For example:
+
[source, json]
----
"candid": "src/rust_hello/src/rust_hello.did",
----
. Add a `+canisters.rust_hello.wasm+` key and specify the location of the compiled WebAssembly file to use for the canister.
+
For example:
+
[source, json]
----
"wasm": "target/wasm32-unknown-unknown/release/rust_hello.wasm",
----
. Modify the `+canisters.rust_hello.type+` key and specify `+custom+` as the canister type.
+
For example:
+
[source, json]
----
"type": "custom"
----
. Remove all of the `+rust_hello_assets+` configuration settings from the file.
+
The sample dapp for this tutorial doesn't use any front-end assets, so you can remove those settings from the configuration file.
+
You can also remove the `+defaults+` and `+dfx+` keys for this tutorial.
+
For example, the configuration file looks like this after you remove the `unused sections:
+
....
include::example$hello-dfx.json[]
....

. Save your changes and close the file to continue.

=== Add a Cargo.toml file to the project

Because we are creating this new Rust project for the {IC} using the {sdk-short-name}, you need to manually create some Rust-specific files in specific locations within the project directory.
Let's start by creating the `+Cargo.toml+` configuration file that describes the packages in our project.

To add a `+Cargo.toml+` configuration file for the project:

. Check that you are still in the root directory for your project, if needed.
. Create a new file in the current directory named `+Cargo.toml+`.
. Open the `+Cargo.toml+` in a text editor.
. Use the `+[workspace]+` key to specify the source file directory for your dapp.
+
For example:
+
[source,toml]
----
[workspace]
members = [
    "src/rust_hello",
]
----
. Save your changes and close the file to continue.

=== Add Rust files to the source directory

Creating a new project creates a default `+src/rust_hello+` directory with a template `+main.mo+`. We'll replace this default dapp with a Rust library `+lib.rs+` package and `+Cargo.toml+` files.

To prepare the source directory with Rust files:

. Check that you are in the root directory for your project, if needed.
. Create a new cargo package using a library template by running the following command:
+
[source, bash]
----
cargo init --lib src/rust_hello
----
+
This command creates a `+src/rust_hello/src+` directory with a library (`+lib.rs+`) package and a `+Cargo.toml+` file in the `+src/rust_hello+` directory.
. Open the `+src/rust_hello/Cargo.toml+` file in a text editor.
+
You use this file to configure the details used to build the Rust package.
+
At a minimum, you need to configure the following sections with basic information about the package name, the crate type, and the version of the {cdk-short-name} libraries to use.
+
--
* `+[package]+`
* `+[lib]+`
* `+[dependencies]+`
--
. Delete the existing `+[dependencies]+` section and replace it with the following:
+
[source,toml]
----
[lib]
crate-type = ["cdylib"]

[dependencies]
ic-cdk = "0.3"
ic-cdk-macros = "0.3"
----
+
NOTE: When you deploy the app later in the tutorial, you might get an error message that the dependency version is wrong. If there is a newer version of the {cdk-short-name}, update the dependencies in the `+src/rust_hello/Cargo.toml+` file to match the latest version.
. Save your changes and close the file to continue.

=== Replace the default dapp

Now that you have the files in place for your Rust dapp, we can replace the template `+main.mo+` dapp with the Rust dapp we want to deploy on the {IC}.

To replace the default dapp:

. Check that you are still in the root directory for your project, if needed.
. Delete the template `+src/rust_hello/main.mo+` file by running the following command:
+
[source,bash]
----
rm src/rust_hello/main.mo
----
. Open the template `+src/rust_hello/src/lib.rs+` file in a text editor and delete the existing content.
. Write a simple `+print+` function that uses the {cdk-short-name} `+query+` macro.
+
For example:
+
[source,rust]
----
#[ic_cdk_macros::query]
fn print() {
    ic_cdk::print("Hello World from DFINITY!");
}
----
. Save your changes and close the file to continue.

== Add an interface description file

Candid is an interface description language (IDL) for interacting with canisters running on the Internet Computer.
Candid files provide a language-independent description of  a canister's interfaces including the names, parameters, and result formats and data types for each function a canister defines.

By adding Candid files to your project, you can ensure that data is properly converted from its definition in Rust to run safely on the {IC}.

To see details about the Candid interface description language syntax, see the link:../candid-guide/candid-intro{outfilesuffix}[_Candid Guide_] or the https://docs.rs/candid/[Candid crate documentation].

To add a Candid file for this tutorial:

. Check that you are still in the root directory for your project, if needed.
. Create a new file in the `+src/rust_hello/src/+` directory named `+rust_hello.did+`.
. Open the `+src/rust_hello/src/rust_hello.did+` file in a text editor.
. Copy and paste the following `+service+` definition for the `+print+` function:
+
[source,did]
----
service : {
    "print": () -> () query;
}
----
+
This definition specifies that the data passed to the `+print+` function is returned unchanged as a `+query+` result.
. Save your changes and close the file to continue.

[[start-the-local-network]]
== Start the {LEE}

Before you can build your project, you need to connect to the {LEE} running in your development environment or the decentralized {IC} mainnet.

To start the {LEE}:

[arabic]
. Check that you are still in the root directory for your project, if needed.
. Start the {LEE} on your computer in the background by running the following command:
+
[source,bash]
----
dfx start --background
----
+
Depending on your platform and local security settings, you might see a warning displayed.
If you are prompted to allow or deny incoming network connections, click *Allow*.

[[register-ids]]
== Register, build, and deploy your project

After you connect to the {LEE} running in your development environment, you can register, build, and deploy your project locally.

To register, build, and deploy:

. Check that you are still in root directory for your project directory, if needed.
. Register, build, and deploy the canisters specified in the `+dfx.json+` file by running the following command:
+
[source,bash]
----
dfx deploy
----
+
The `+dfx deploy+` command output displays information about each of the operations it performs similar to the following excerpt:
+
....
Creating a wallet canister on the local network.
The wallet canister on the "local" network for user "pubs_user_id" is "rwlgt-iiaaa-aaaaa-aaaaa-cai"
Deploying all canisters.
Creating canisters...
Creating canister "rust_hello"...
"rust_hello" canister created with canister id: "rrkah-fqaaa-aaaaa-aaaaq-cai"
Building canisters...
Executing 'cargo build --target wasm32-unknown-unknown --package rust_hello --release'
    Updating crates.io index
   Compiling unicode-xid v0.2.2
   ...
Building canisters...
Executing 'cargo build --target wasm32-unknown-unknown --package rust_hello --release'
   Compiling rust_hello v0.1.0 (/Users/lisagunn/CDK-RS-APR-2021/rust_hello/src/rust_hello)
    Finished release [optimized] target(s) in 1.26s
Installing canisters...
Creating UI canister on the local network.
The UI canister on the "local" network is "rkp4c-7iaaa-aaaaa-aaaca-cai"
Installing code for canister rust_hello, with canister_id r7inp-6aaaa-aaaaa-aaabq-cai
Deployed canisters.
....

////
////
== Optimize and test the dapp

At this point, you have a dapp compiled to WebAssembly that has not been optimized for deployment on the {IC}.

To optimize and test the resulting canister:

. Check that you are still in root directory for your project directory, if needed.
. Install the `+ic-cdk-optimizer+` crate by running the following command:
+
[source,bash]
----
cargo install ic-cdk-optimizer
----
+
This package optimizes your Rust code to reduce the size of the WebAssembly output to ensure your dapp can be uploaded as a canister.
. Create a release directory within the `+src/rust_hello+` directory by running the following command:
+
[source,bash]
----
mkdir -p src/rust_hello/target/wasm32-unknown-unknown/release/
----
. Optimize the code within the `+target/rust_hello+` directory by running the following command:
+
[source,bash]
----
ic-cdk-optimizer target/wasm32-unknown-unknown/release/rust_hello.wasm -o target/wasm32-unknown-unknown/release/rust_hello-opt.wasm
----
////
////

== Test the dapp

To test the deployed dapp locally:

. Check that you are still in root directory for your project directory, if needed.
. Call the `+print+` function in the dapp by running the following command:
+
[source,bash]
----
dfx canister call rust_hello print
----
. Verify that the call to the `+rust_hello+` canister `+print+` function displays the `+Hello World from DFINITY!+` greeting.
+
For example:
+
....
[Canister ryjl3-tyaaa-aaaaa-aaaba-cai] Hello World from DFINITY!
()
....

== Stop the {LEE}

After testing the application, you can stop the {LEE} so that it doesn’t continue running in the background.

To stop the {LEE}:

. In the terminal that displays network operations, press Control-C to interrupt the {LEE} process.

. Stop the {LEE} running on your computer by running the following command:
+
[source,bash]
----
dfx stop
----

////